package sun.security.util.resources;

import java.util.ListResourceBundle;

public final class security_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Principal.", "\tPrincipal: " },
            { ".Private.Credential.", "\tCredencial Privada: " },
            { ".Private.Credential.inaccessible.", "\tCredencial Privada Inaccesible\n" },
            { ".Private.Credentials.inaccessible.", "\tCredenciales Privadas Inaccesibles\n" },
            { ".Public.Credential.", "\tCredencial P\u00FAblica: " },
            { "CredOwner.Principal.Class.class.Principal.Name.name", "CredOwner:\n\tClase de Principal = {0}\n\tNombre de Principal = {1}" },
            { "Credential.Class.not.followed.by.a.Principal.Class.and.Name", "La clase de credencial no va seguida de una clase y nombre de principal" },
            { "Invalid.null.input.name", "Entrada nula no v\u00E1lida: nombre" },
            { "LPARAM", "(" },
            { "Login.Failure.all.modules.ignored", "Fallo en inicio de sesi\u00F3n: se han ignorado todos los m\u00F3dulos" },
            { "LoginModuleControlFlag.", "LoginModuleControlFlag: " },
            { "NEWLINE", "\n" },
            { "No.LoginModules.configured.for.name", "No se han configurado LoginModules para {0}" },
            { "PKCS11.Token.providerName.Password.", "Contrase\u00F1a del Token PKCS11 [{0}]: " },
            { "Principal.Class.not.followed.by.a.Principal.Name", "La clase de principal no va seguida de un nombre de principal" },
            { "Principal.Name.missing.end.quote", "Faltan las comillas finales en el nombre de principal" },
            { "Principal.Name.must.be.surrounded.by.quotes", "El nombre de principal debe ir entre comillas" },
            { "PrivateCredentialPermission.Principal.Class.can.not.be.a.wildcard.value.if.Principal.Name.is.not.a.wildcard.value", "La clase de principal PrivateCredentialPermission no puede ser un valor comod\u00EDn (*) si el nombre de principal no lo es tambi\u00E9n" },
            { "RPARAM", ")" },
            { "SPACE", " " },
            { "SignedBy.has.empty.alias", "SignedBy tiene un alias vac\u00EDo" },
            { "Subject.", "Asunto:\n" },
            { "Subject.is.read.only", "El asunto es de s\u00F3lo lectura" },
            { "actions.can.only.be.read.", "las acciones s\u00F3lo pueden 'leerse'" },
            { "alias.name.not.provided.pe.name.", "no se ha proporcionado el nombre de alias ({0})" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.class", "intentando agregar un objeto que no es una instancia de {0}" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.java.security.Principal.to.a.Subject.s.Principal.Set", "intentando agregar un objeto que no es una instancia de java.security.Principal al juego principal de un asunto" },
            { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "no se puede especificar Principal con una clase de comod\u00EDn sin un nombre de comod\u00EDn" },
            { "duplicate.keystore.domain.name", "nombre de dominio de almac\u00E9n de claves duplicado: {0}" },
            { "duplicate.keystore.name", "nombre de almac\u00E9n de claves duplicado: {0}" },
            { "expected.codeBase.or.SignedBy.or.Principal", "se esperaba codeBase o SignedBy o Principal" },
            { "expected.expect.read.end.of.file.", "se esperaba [{0}], se ha le\u00EDdo [final de archivo]" },
            { "expected.keystore.provider", "se esperaba un proveedor de almac\u00E9n de claves" },
            { "expected.keystore.type", "se esperaba un tipo de almac\u00E9n de claves" },
            { "expected.permission.entry", "se esperaba un permiso de entrada" },
            { "expected.read.end.of.file.", "se esperaba [;], se ha le\u00EDdo [final de archivo]" },
            { "invalid.null.AccessControlContext.provided", "se ha proporcionado un AccessControlContext nulo no v\u00E1lido" },
            { "invalid.null.CallbackHandler.provided", "se ha proporcionado CallbackHandler nulo no v\u00E1lido" },
            { "invalid.null.Class.provided", "se ha proporcionado una clase nula no v\u00E1lida" },
            { "invalid.null.Subject.provided", "se ha proporcionado un asunto nulo no v\u00E1lido" },
            { "invalid.null.action.provided", "se ha proporcionado una acci\u00F3n nula no v\u00E1lida" },
            { "invalid.null.input.s.", "entradas nulas no v\u00E1lidas" },
            { "java.security.policy.error.adding.Entry.message", "java.security.policy: error al agregar una entrada:\n\t{0}" },
            { "java.security.policy.error.adding.Permission.perm.message", "java.security.policy: error al agregar un permiso, {0}:\n\t{1}" },
            { "java.security.policy.error.parsing.policy.message", "java.security.policy: error de an\u00E1lisis de {0}:\n\t{1}" },
            { "keystorePasswordURL.can.not.be.specified.without.also.specifying.keystore", "keystorePasswordURL no puede especificarse sin especificar tambi\u00E9n el almac\u00E9n de claves" },
            { "line.number.expected.expect.found.actual.", "l\u00EDnea {0}: se esperaba [{1}], se ha encontrado [{2}]" },
            { "line.number.msg", "l\u00EDnea {0}: {1}" },
            { "multiple.Codebase.expressions", "expresiones m\u00FAltiples de CodeBase" },
            { "multiple.SignedBy.expressions", "expresiones m\u00FAltiples de SignedBy" },
            { "null.principalClass.or.principalName", "principalClass o principalName nulos" },
            { "null.subject.logout.called.before.login", "asunto nulo - se ha llamado al cierre de sesi\u00F3n antes del inicio de sesi\u00F3n" },
            { "number.", "n\u00FAmero " },
            { "permission.name.name.syntax.invalid.", "sintaxis de nombre de permiso [{0}] no v\u00E1lida: " },
            { "provided.null.OID.map", "mapa de OID proporcionado nulo" },
            { "provided.null.keyword.map", "mapa de palabras clave proporcionado nulo" },
            { "provided.null.name", "se ha proporcionado un nombre nulo" },
            { "substitution.value.prefix.unsupported", "valor de sustituci\u00F3n, {0}, no soportado" },
            { "type.can.t.be.null", "el tipo no puede ser nulo" },
            { "unable.to.access.LoginModule.", "no se ha podido acceder a LoginModule: " },
            { "unable.to.find.LoginModule.class.", "no se ha encontrado la clase LoginModule: " },
            { "unable.to.instantiate.LoginModule", "no se ha podido instanciar LoginModule" },
            { "unable.to.instantiate.LoginModule.", "no se ha podido instanciar LoginModule: " },
            { "unable.to.instantiate.LoginModule.module.because.it.does.not.provide.a.no.argument.constructor", "no se ha podido instanciar LoginModule, {0}, porque no incluye un constructor sin argumentos" },
            { "unable.to.instantiate.Subject.based.policy", "no se ha podido instanciar una pol\u00EDtica basada en asunto" },
            { "unable.to.perform.substitution.on.alias.suffix", "no se puede realizar la sustituci\u00F3n en el alias, {0}" },
        };
    }
}
