package sun.security.util.resources;

import java.util.ListResourceBundle;

public final class security_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Principal.", "\tPrincipal: " },
            { ".Private.Credential.", "\tCredenziale privata: " },
            { ".Private.Credential.inaccessible.", "\tImpossibile accedere alla credenziale privata\n" },
            { ".Private.Credentials.inaccessible.", "\tImpossibile accedere alle credenziali private\n" },
            { ".Public.Credential.", "\tCredenziale pubblica: " },
            { "CredOwner.Principal.Class.class.Principal.Name.name", "CredOwner:\n\tclasse Principal = {0}\n\tNome Principal = {1}" },
            { "Credential.Class.not.followed.by.a.Principal.Class.and.Name", "la classe di credenziali non \u00E8 seguita da un nome e una classe di principal" },
            { "Invalid.null.input.name", "Input nullo non valido: nome" },
            { "LPARAM", "(" },
            { "Login.Failure.all.modules.ignored", "Errore di login: tutti i moduli sono stati ignorati" },
            { "LoginModuleControlFlag.", "LoginModuleControlFlag: " },
            { "NEWLINE", "\n" },
            { "No.LoginModules.configured.for.name", "Nessun LoginModules configurato per {0}" },
            { "PKCS11.Token.providerName.Password.", "Password per token PKCS11 [{0}]: " },
            { "Principal.Class.not.followed.by.a.Principal.Name", "la classe di principal non \u00E8 seguita da un nome principal" },
            { "Principal.Name.missing.end.quote", "apice di chiusura del nome principal mancante" },
            { "Principal.Name.must.be.surrounded.by.quotes", "il nome principal deve essere compreso tra apici" },
            { "PrivateCredentialPermission.Principal.Class.can.not.be.a.wildcard.value.if.Principal.Name.is.not.a.wildcard.value", "la classe principal PrivateCredentialPermission non pu\u00F2 essere un valore carattere jolly (*) se il nome principal a sua volta non \u00E8 un valore carattere jolly (*)" },
            { "RPARAM", ")" },
            { "SPACE", " " },
            { "SignedBy.has.empty.alias", "SignedBy presenta un alias vuoto" },
            { "Subject.", "Oggetto:\n" },
            { "Subject.is.read.only", "L'oggetto \u00E8 di sola lettura" },
            { "actions.can.only.be.read.", "le azioni possono essere solamente 'lette'" },
            { "alias.name.not.provided.pe.name.", "impossibile fornire nome alias ({0})" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.class", "si \u00E8 tentato di aggiungere un oggetto che non \u00E8 un''istanza di {0}" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.java.security.Principal.to.a.Subject.s.Principal.Set", "si \u00E8 tentato di aggiungere un oggetto che non \u00E8 un'istanza di java.security.Principal a un set principal dell'oggetto" },
            { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "impossibile specificare un principal con una classe carattere jolly senza un nome carattere jolly" },
            { "duplicate.keystore.domain.name", "nome dominio keystore duplicato: {0}" },
            { "duplicate.keystore.name", "nome keystore duplicato: {0}" },
            { "expected.codeBase.or.SignedBy.or.Principal", "previsto codeBase o SignedBy o principal" },
            { "expected.expect.read.end.of.file.", "previsto [{0}], letto [end of file]" },
            { "expected.keystore.provider", "provider di keystore previsto" },
            { "expected.keystore.type", "tipo keystore previsto" },
            { "expected.permission.entry", "prevista voce di autorizzazione" },
            { "expected.read.end.of.file.", "previsto [;], letto [end of file]" },
            { "invalid.null.AccessControlContext.provided", "fornito un valore nullo non valido per AccessControlContext" },
            { "invalid.null.CallbackHandler.provided", "fornito un valore nullo non valido per CallbackHandler" },
            { "invalid.null.Class.provided", "fornita una classe nulla non valida" },
            { "invalid.null.Subject.provided", "fornito un valore nullo non valido per l'oggetto" },
            { "invalid.null.action.provided", "fornita un'azione nulla non valida" },
            { "invalid.null.input.s.", "input nullo/i non valido/i" },
            { "java.security.policy.error.adding.Entry.message", "java.security.policy: errore durante l''aggiunta della voce:\n\t{0}" },
            { "java.security.policy.error.adding.Permission.perm.message", "java.security.policy: errore durante l''aggiunta dell''autorizzazione {0}:\n\t{1}" },
            { "java.security.policy.error.parsing.policy.message", "java.security.policy: errore durante l''analisi di {0}:\n\t{1}" },
            { "keystorePasswordURL.can.not.be.specified.without.also.specifying.keystore", "Impossibile specificare keystorePasswordURL senza specificare anche il keystore" },
            { "line.number.expected.expect.found.actual.", "riga {0}: previsto [{1}], trovato [{2}]" },
            { "line.number.msg", "riga {0}: {1}" },
            { "multiple.Codebase.expressions", "espressioni Codebase multiple" },
            { "multiple.SignedBy.expressions", "espressioni SignedBy multiple" },
            { "null.principalClass.or.principalName", "principalClass o principalName nullo" },
            { "null.subject.logout.called.before.login", "oggetto nullo - il logout \u00E8 stato richiamato prima del login" },
            { "number.", "numero " },
            { "permission.name.name.syntax.invalid.", "sintassi [{0}] non valida per il nome autorizzazione: " },
            { "provided.null.OID.map", "specificata mappa OID null" },
            { "provided.null.keyword.map", "specificata mappa parole chiave null" },
            { "provided.null.name", "il nome fornito \u00E8 nullo" },
            { "substitution.value.prefix.unsupported", "valore sostituzione, {0}, non supportato" },
            { "type.can.t.be.null", "il tipo non pu\u00F2 essere nullo" },
            { "unable.to.access.LoginModule.", "impossibile accedere a LoginModule " },
            { "unable.to.find.LoginModule.class.", "impossibile trovare la classe LoginModule: " },
            { "unable.to.instantiate.LoginModule", "impossibile creare un'istanza di LoginModule" },
            { "unable.to.instantiate.LoginModule.", "impossibile creare un'istanza di LoginModule: " },
            { "unable.to.instantiate.LoginModule.module.because.it.does.not.provide.a.no.argument.constructor", "impossibile creare un''istanza di LoginModule {0} in quanto non restituisce un argomento vuoto per il costruttore" },
            { "unable.to.instantiate.Subject.based.policy", "impossibile creare un'istanza dei criteri basati sull'oggetto" },
            { "unable.to.perform.substitution.on.alias.suffix", "impossibile eseguire una sostituzione sull''alias, {0}" },
        };
    }
}
