package sun.security.util.resources;

import java.util.ListResourceBundle;

public final class security_sv extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Principal.", "\tIdentitetshavare: " },
            { ".Private.Credential.", "\tPrivat inloggning: " },
            { ".Private.Credential.inaccessible.", "\tPrivat inloggning \u00E4r inte tillg\u00E4nglig\n" },
            { ".Private.Credentials.inaccessible.", "\tPrivat inloggning \u00E4r inte tillg\u00E4nglig\n" },
            { ".Public.Credential.", "\tOffentlig inloggning: " },
            { "CredOwner.Principal.Class.class.Principal.Name.name", "CredOwner:\n\tIdentitetshavareklass = {0}\n\tIdentitetshavarenamn = {1}" },
            { "Credential.Class.not.followed.by.a.Principal.Class.and.Name", "Inloggningsuppgiftsklassen f\u00F6ljs inte av klass eller namn f\u00F6r identitetshavare" },
            { "Invalid.null.input.name", "Ogiltiga null-indata: namn" },
            { "LPARAM", "(" },
            { "Login.Failure.all.modules.ignored", "Inloggningsfel: alla moduler ignoreras" },
            { "LoginModuleControlFlag.", "LoginModuleControlFlag: " },
            { "NEWLINE", "\n" },
            { "No.LoginModules.configured.for.name", "Inga inloggningsmoduler har konfigurerats f\u00F6r {0}" },
            { "PKCS11.Token.providerName.Password.", "L\u00F6senord f\u00F6r PKCS11-token [{0}]: " },
            { "Principal.Class.not.followed.by.a.Principal.Name", "Identitetshavareklassen f\u00F6ljs inte av n\u00E5got identitetshavarenamn" },
            { "Principal.Name.missing.end.quote", "Identitetshavarenamnet saknar avslutande citattecken" },
            { "Principal.Name.must.be.surrounded.by.quotes", "Identitetshavarenamnet m\u00E5ste anges inom citattecken" },
            { "PrivateCredentialPermission.Principal.Class.can.not.be.a.wildcard.value.if.Principal.Name.is.not.a.wildcard.value", "Identitetshavareklassen PrivateCredentialPermission kan inte ha n\u00E5got jokertecken (*) om inte namnet p\u00E5 identitetshavaren anges med jokertecken (*)" },
            { "RPARAM", ")" },
            { "SPACE", " " },
            { "SignedBy.has.empty.alias", "SignedBy har ett tomt alias" },
            { "Subject.", "Innehavare:\n" },
            { "Subject.is.read.only", "Innehavare \u00E4r skrivskyddad" },
            { "actions.can.only.be.read.", "\u00E5tg\u00E4rder kan endast 'l\u00E4sas'" },
            { "alias.name.not.provided.pe.name.", "aliasnamn ej angivet ({0})" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.class", "f\u00F6rs\u00F6ker l\u00E4gga till ett objekt som inte \u00E4r en instans av {0}" },
            { "attempting.to.add.an.object.which.is.not.an.instance.of.java.security.Principal.to.a.Subject.s.Principal.Set", "f\u00F6rs\u00F6k att l\u00E4gga till ett objekt som inte \u00E4r en instans av java.security.Principal till ett subjekts upps\u00E4ttning av identitetshavare" },
            { "can.not.specify.Principal.with.a.wildcard.class.without.a.wildcard.name", "kan inte ange identitetshavare med en jokerteckenklass utan ett jokerteckennamn" },
            { "duplicate.keystore.domain.name", "dom\u00E4nnamn f\u00F6r dubbelt nyckellager: {0}" },
            { "duplicate.keystore.name", "namn f\u00F6r dubbelt nyckellager: {0}" },
            { "expected.codeBase.or.SignedBy.or.Principal", "f\u00F6rv\u00E4ntad codeBase eller SignedBy eller identitetshavare" },
            { "expected.expect.read.end.of.file.", "f\u00F6rv\u00E4ntade [{0}], l\u00E4ste [filslut]" },
            { "expected.keystore.provider", "nyckellagerleverant\u00F6r f\u00F6rv\u00E4ntades" },
            { "expected.keystore.type", "f\u00F6rv\u00E4ntad nyckellagertyp" },
            { "expected.permission.entry", "f\u00F6rv\u00E4ntade beh\u00F6righetspost" },
            { "expected.read.end.of.file.", "f\u00F6rv\u00E4ntade [;], l\u00E4ste [filslut]" },
            { "invalid.null.AccessControlContext.provided", "ogiltigt null-AccessControlContext" },
            { "invalid.null.CallbackHandler.provided", "ogiltig null-CallbackHandler" },
            { "invalid.null.Class.provided", "ogiltig null-klass" },
            { "invalid.null.Subject.provided", "ogiltig null-subjekt" },
            { "invalid.null.action.provided", "ogiltig null-funktion" },
            { "invalid.null.input.s.", "ogiltiga null-indata" },
            { "java.security.policy.error.adding.Entry.message", "java.security.policy: fel vid till\u00E4gg av post:\n\t{0}" },
            { "java.security.policy.error.adding.Permission.perm.message", "java.security.policy: fel vid till\u00E4gg av beh\u00F6righet, {0}:\n\t{1}" },
            { "java.security.policy.error.parsing.policy.message", "java.security.policy: fel vid tolkning av {0}:\n\t{1}" },
            { "keystorePasswordURL.can.not.be.specified.without.also.specifying.keystore", "kan inte ange keystorePasswordURL utan att ange nyckellager" },
            { "line.number.expected.expect.found.actual.", "rad {0}: f\u00F6rv\u00E4ntade [{1}], hittade [{2}]" },
            { "line.number.msg", "rad {0}: {1}" },
            { "multiple.Codebase.expressions", "flera CodeBase-uttryck" },
            { "multiple.SignedBy.expressions", "flera SignedBy-uttryck" },
            { "null.principalClass.or.principalName", "null-principalClass eller -principalName" },
            { "null.subject.logout.called.before.login", "null-subjekt - utloggning anropades f\u00F6re inloggning" },
            { "number.", "nummer" },
            { "permission.name.name.syntax.invalid.", "syntaxen f\u00F6r beh\u00F6righetsnamnet [{0}] \u00E4r ogiltig: " },
            { "provided.null.OID.map", "null-OID-mappning angavs" },
            { "provided.null.keyword.map", "nullnyckelordsmappning angavs" },
            { "provided.null.name", "null-namn angavs" },
            { "substitution.value.prefix.unsupported", "ers\u00E4ttningsv\u00E4rde, {0}, st\u00F6ds ej" },
            { "type.can.t.be.null", "typen kan inte vara null" },
            { "unable.to.access.LoginModule.", "ingen \u00E5tkomst till LoginModule: " },
            { "unable.to.find.LoginModule.class.", "hittar inte LoginModule-klassen: " },
            { "unable.to.instantiate.LoginModule", "kan inte instansiera LoginModule" },
            { "unable.to.instantiate.LoginModule.", "kan inte instansiera LoginModule: " },
            { "unable.to.instantiate.LoginModule.module.because.it.does.not.provide.a.no.argument.constructor", "kan inte instansiera LoginModule, {0}, eftersom den inte tillhandah\u00E5ller n\u00E5gon icke-argumentskonstruktor" },
            { "unable.to.instantiate.Subject.based.policy", "kan inte instansiera subjektbaserad policy" },
            { "unable.to.perform.substitution.on.alias.suffix", "kan ej ers\u00E4tta alias, {0}" },
        };
    }
}
