package sun.security.tools.keytool.resources;

import java.util.ListResourceBundle;

public final class keytool_sv extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Empty.value.", "(Tomt v\u00E4rde)" },
            { ".OPTION.", " [OPTION]..." },
            { ".PATTERN.printX509Cert.with.weak", "\u00C4gare: {0}\nUtf\u00E4rdare: {1}\nSerienummer: {2}\nGiltigt fr\u00E5n: {3}, till: {4}\nCertifikatfingeravtryck:\n\t SHA1: {5}\n\t SHA256: {6}\nSignaturalgoritmnamn: {7}\nAlgoritm f\u00F6r \u00F6ppen nyckel f\u00F6r \u00E4mne: {8}\nVersion: {9}" },
            { ".RETURN.if.same.as.for.otherAlias.", "\t(RETURN om det \u00E4r det samma som f\u00F6r <{0}>)" },
            { ".RETURN.if.same.as.keystore.password.", "\t(RETURN om det \u00E4r identiskt med nyckellagerl\u00F6senordet):  " },
            { ".Storing.ksfname.", "[Lagrar {0}]" },
            { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "* Integriteten f\u00F6r den information som lagras i srckeystore*\n* har INTE verifierats!  Om du vill verifiera dess integritet *\n* m\u00E5ste du ange l\u00F6senordet f\u00F6r srckeystore.                *" },
            { ".The.integrity.of.the.information.stored.in.your.keystore.", "* Integriteten f\u00F6r den information som lagras i nyckellagerfilen  *\n* har INTE verifierats!  Om du vill verifiera dess integritet *\n* m\u00E5ste du ange l\u00F6senordet f\u00F6r nyckellagret.                  *" },
            { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" },
            { ".defaultValue.", "  [{0}]:  " },
            { ".is.not.trusted.", "... \u00E4r inte betrott. " },
            { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "-keypass och -new kan inte anges om -storetype \u00E4r {0}" },
            { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "-keypasswd-kommandon st\u00F6ds inte om -storetype \u00E4r PKCS12" },
            { ".keystore.must.be.NONE.if.storetype.is.{0}", "-keystore m\u00E5ste vara NONE om -storetype \u00E4r {0}" },
            { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "-storepasswd- och -keypasswd-kommandon st\u00F6ds inte om -storetype \u00E4r {0}" },
            { "Alias.alias.does.not.exist", "Aliaset <{0}> finns inte" },
            { "Alias.alias.has.no.certificate", "Aliaset <{0}> saknar certifikat" },
            { "Alias.alias.has.no.key", "Aliaset <{0}> saknar nyckel" },
            { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "Aliaset <{0}> refererar till en posttyp som inte \u00E4r n\u00E5gon privat nyckelpost. Kommandot -keyclone har endast st\u00F6d f\u00F6r kloning av privata nyckelposter" },
            { "Alias.name.alias", "Aliasnamn: {0}" },
            { "CRLs.", "CRL:er:" },
            { "Cannot.derive.signature.algorithm", "Kan inte h\u00E4rleda signaturalgoritm" },
            { "Cannot.find.environment.variable.", "Hittar inte milj\u00F6variabel: " },
            { "Cannot.find.file.", "Hittar inte fil: " },
            { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "Certifikatet finns redan i nyckellagerfilen under aliaset <{0}>" },
            { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "Certifikatet finns redan i den systemomsp\u00E4nnande CA-nyckellagerfilen under aliaset <{0}>" },
            { "Certificate.chain.in.reply.does.not.verify.", "Certifikatskedjan i svaret g\u00E5r inte att verifiera: " },
            { "Certificate.chain.length.", "L\u00E4ngd p\u00E5 certifikatskedja: " },
            { "Certificate.fingerprint.SHA.256.", "Certifikatfingeravtryck (SHA-256): " },
            { "Certificate.i.1.", "Certifikat[{0,number,integer}]:" },
            { "Certificate.not.imported.alias.alias.already.exists", "Certifikatet importerades inte. Aliaset <{0}> finns redan" },
            { "Certificate.owner.", "Certifikat\u00E4gare: " },
            { "Certificate.reply.and.certificate.in.keystore.are.identical", "Certifikatsvaret och certifikatet i nyckellagret \u00E4r identiska" },
            { "Certificate.reply.does.not.contain.public.key.for.alias.", "Certifikatsvaret inneh\u00E5ller inte n\u00E5gon \u00F6ppen nyckel f\u00F6r <{0}>" },
            { "Certificate.reply.was.installed.in.keystore", "Certifikatsvaret har installerats i nyckellagret" },
            { "Certificate.reply.was.not.installed.in.keystore", "Certifikatsvaret har inte installerats i nyckellagret" },
            { "Certificate.stored.in.file.filename.", "Certifikatet har lagrats i filen <{0}>" },
            { "Certificate.was.added.to.keystore", "Certifikatet har lagts till i nyckellagret" },
            { "Certificate.was.not.added.to.keystore", "Certifikatet har inte lagts till i nyckellagret" },
            { "Certification.request.stored.in.file.filename.", "Certifikatbeg\u00E4ran har lagrats i filen <{0}>" },
            { "Changes.an.entry.s.alias", "\u00C4ndrar postalias" },
            { "Changes.the.key.password.of.an.entry", "\u00C4ndrar nyckell\u00F6senordet f\u00F6r en post" },
            { "Changes.the.store.password.of.a.keystore", "\u00C4ndrar lagerl\u00F6senordet f\u00F6r ett nyckellager" },
            { "Clones.a.key.entry", "Klonar en nyckelpost" },
            { "Command.option.flag.needs.an.argument.", "Kommandoalternativet {0} beh\u00F6ver ett argument." },
            { "Commands.", "Kommandon:" },
            { "Creating.keystore.entry.for.id.getName.", "Skapar nyckellagerpost f\u00F6r <{0}> ..." },
            { "Creation.date.keyStore.getCreationDate.alias.", "Skapat den: {0,date}" },
            { "Deletes.an.entry", "Tar bort en post" },
            { "Destination.alias.dest.already.exists", "Destinationsaliaset <{0}> finns redan" },
            { "Do.you.still.want.to.add.it.no.", "Vill du fortfarande l\u00E4gga till det? [nej]:  " },
            { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "Vill du fortfarande l\u00E4gga till det i ditt eget nyckellagret? [nej]:  " },
            { "Empty.input", "Inga indata" },
            { "Enter.alias.name.", "Ange aliasnamn:  " },
            { "Enter.destination.keystore.password.", "Ange nyckellagerl\u00F6senord f\u00F6r destination:  " },
            { "Enter.key.password.for.alias.", "Ange nyckell\u00F6senord f\u00F6r <{0}>" },
            { "Enter.keystore.password.", "Ange nyckellagerl\u00F6senord:  " },
            { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "Ange ett nytt aliasnamn\t(skriv RETURN f\u00F6r att avbryta importen av denna post):  " },
            { "Enter.prompt.alias.name.", "Ange aliasnamn f\u00F6r {0}:  " },
            { "Enter.source.keystore.password.", "Ange l\u00F6senord f\u00F6r k\u00E4llnyckellagret:  " },
            { "Enter.the.password.to.be.stored.", "Ange det l\u00F6senord som ska lagras:  " },
            { "Entry.for.alias.alias.not.imported.", "Posten f\u00F6r alias {0} har inte importerats." },
            { "Entry.for.alias.alias.successfully.imported.", "Posten f\u00F6r alias {0} har importerats." },
            { "Entry.type.type.", "Posttyp: {0}" },
            { "Existing.entry.alias.alias.exists.overwrite.no.", "Aliaset {0} finns redan. Vill du skriva \u00F6ver det? [nej]:  " },
            { "Exports.certificate", "Exporterar certifikat" },
            { "Extension.Request.", "Till\u00E4ggsbeg\u00E4ran:" },
            { "Extensions.", "Till\u00E4gg: " },
            { "Failed.to.establish.chain.from.reply", "Kunde inte uppr\u00E4tta kedja fr\u00E5n svaret" },
            { "Failed.to.parse.input", "Kunde inte tolka indata" },
            { "Generated.keyAlgName.secret.key", "Genererade {0} hemlig nyckel" },
            { "Generated.keysize.bit.keyAlgName.secret.key", "Genererade {0}-bitars {1} hemlig nyckel" },
            { "Generates.CRL", "Genererar CRL" },
            { "Generates.a.certificate.request", "Genererar certifikatbeg\u00E4ran" },
            { "Generates.a.key.pair", "Genererar nyckelpar" },
            { "Generates.a.secret.key", "Genererar hemlig nyckel" },
            { "Generates.a.self.signed.certificate", "Genererar ett sj\u00E4lvsignerat certifikat" },
            { "Generates.certificate.from.a.certificate.request", "Genererar certifikat fr\u00E5n certifikatbeg\u00E4ran" },
            { "Generating.keysize.bit.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.validality.days.for", "Genererar {0} bitars {1}-nyckelpar och sj\u00E4lvsignerat certifikat ({2}) med en giltighet p\u00E5 {3} dagar\n\tf\u00F6r: {4}" },
            { "Illegal.option.", "Otill\u00E5tet alternativ:  " },
            { "Illegal.startdate.value", "Otill\u00E5tet v\u00E4rde f\u00F6r startdatum" },
            { "Illegal.value.", "Otill\u00E5tet v\u00E4rde: " },
            { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "Kommandoimporten slutf\u00F6rd: {0} poster har importerats, {1} poster var felaktiga eller annullerades" },
            { "Imports.a.certificate.or.a.certificate.chain", "Importerar ett certifikat eller en certifikatkedja" },
            { "Imports.a.password", "Importerar ett l\u00F6senord" },
            { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "Importerar poster fr\u00E5n identitetsdatabas i JDK 1.1.x-format" },
            { "Imports.one.or.all.entries.from.another.keystore", "Importerar en eller alla poster fr\u00E5n annat nyckellager" },
            { "Incomplete.certificate.chain.in.reply", "Ofullst\u00E4ndig certifikatskedja i svaret" },
            { "Input.not.an.X.509.certificate", "Indata \u00E4r inte ett X.509-certifikat" },
            { "Install.reply.anyway.no.", "Vill du installera svaret \u00E4nd\u00E5? [nej]:  " },
            { "Is.name.correct.", "\u00C4r {0} korrekt?" },
            { "Key.and.Certificate.Management.Tool", "Hanteringsverktyg f\u00F6r nycklar och certifikat" },
            { "Key.pair.not.generated.alias.alias.already.exists", "Nyckelparet genererades inte. Aliaset <{0}> finns redan" },
            { "Key.password.is.too.short.must.be.at.least.6.characters", "Nyckell\u00F6senordet \u00E4r f\u00F6r kort - det m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "Key.password.must.be.at.least.6.characters", "Nyckell\u00F6senordet m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "Keystore.entry.for.id.getName.already.exists", "Nyckellagerpost f\u00F6r <{0}> finns redan" },
            { "Keystore.file.does.not.exist.", "Nyckellagerfilen finns inte: " },
            { "Keystore.file.exists.but.is.empty.", "Nyckellagerfilen finns, men \u00E4r tom: " },
            { "Keystore.password.is.too.short.must.be.at.least.6.characters", "Nyckellagerl\u00F6senordet \u00E4r f\u00F6r kort - det m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "Keystore.password.must.be.at.least.6.characters", "Nyckellagerl\u00F6senordet m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "Keystore.provider.", "Nyckellagerleverant\u00F6r: " },
            { "Keystore.type.", "Nyckellagertyp: " },
            { "Lists.entries.in.a.keystore", "Visar lista \u00F6ver poster i nyckellager" },
            { "Must.not.specify.both.v.and.rfc.with.list.command", "Kan inte specificera b\u00E5de -v och -rfc med 'list'-kommandot" },
            { "Must.specify.alias", "Du m\u00E5ste ange alias" },
            { "Must.specify.destination.alias", "Du m\u00E5ste ange destinationsalias" },
            { "NEWLINE", "\n" },
            { "NO", "NEJ" },
            { "New.certificate.self.signed.", "Nytt certifikat (sj\u00E4lvsignerat):" },
            { "New.password.must.be.at.least.6.characters", "Det nya l\u00F6senordet m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "New.prompt.", "Nytt {0}: " },
            { "No.certificate.from.the.SSL.server", "Inget certifikat fr\u00E5n SSL-servern" },
            { "No.entries.from.identity.database.added", "Inga poster fr\u00E5n identitetsdatabasen har lagts till" },
            { "Not.X.509.certificate", "Inte ett X.509-certifikat" },
            { "Not.a.signed.jar.file", "Ingen signerad jar-fil" },
            { "Odd.number.of.hex.digits.found.", "Udda antal hex-siffror p\u00E5tr\u00E4ffades: " },
            { "Options.", "Alternativ:" },
            { "PKCS.10.with.weak", "PKCS #10-certifikatbeg\u00E4ran (version 1.0)\n\u00C4mne: %1$s\nFormat: %2$s\n\u00D6ppen nyckel: %3$s\nSignaturalgoritm: %4$s\n" },
            { "Password.is.too.short.must.be.at.least.6.characters", "L\u00F6senordet \u00E4r f\u00F6r kort - det m\u00E5ste inneh\u00E5lla minst 6 tecken" },
            { "Passwords.must.differ", "L\u00F6senorden m\u00E5ste vara olika" },
            { "Please.provide.keysize.for.secret.key.generation", "Ange -keysize f\u00F6r att skapa hemlig nyckel" },
            { "Please.specify.srckeystore", "Ange -srckeystore" },
            { "Prints.the.content.of.a.CRL.file", "Skriver ut inneh\u00E5llet i en CRL-fil" },
            { "Prints.the.content.of.a.certificate", "Skriver ut inneh\u00E5llet i ett certifikat" },
            { "Prints.the.content.of.a.certificate.request", "Skriver ut inneh\u00E5llet i en certifikatbeg\u00E4ran" },
            { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "Ett problem uppstod vid importen av posten f\u00F6r alias {0}: {1}.\nPosten {0} har inte importerats." },
            { "Public.keys.in.reply.and.keystore.don.t.match", "De offentliga nycklarna i svaret och nyckellagret matchar inte varandra" },
            { "Re.enter.new.password.", "Ange det nya l\u00F6senordet igen: " },
            { "Re.enter.new.prompt.", "Ange nytt {0} igen: " },
            { "Re.enter.password.", "Ange l\u00F6senord igen: " },
            { "Reply.has.no.certificates", "Svaret saknar certifikat" },
            { "SSL.server.host.and.port", "SSL-serverv\u00E4rd och -port" },
            { "STAR", "*******************************************" },
            { "STARNN", "*******************************************\n\n" },
            { "Secret.key.not.generated.alias.alias.already.exists", "Den hemliga nyckeln har inte genererats eftersom aliaset <{0}> redan finns" },
            { "Serial.ID.of.cert.to.revoke", "Serienummer p\u00E5 certifikat som ska \u00E5terkallas" },
            { "Signature.", "Signatur:" },
            { "Signer.d.", "Undertecknare %d:" },
            { "Source.keystore.file.exists.but.is.empty.", "Nyckellagrets k\u00E4llfil finns, men \u00E4r tom: " },
            { "Submit.this.to.your.CA", "Skicka detta till certifikatutf\u00E4rdaren" },
            { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "Destinationsnyckellagret pkcs12 har olika storepass och keypass. F\u00F6rs\u00F6k igen med -destkeypass angivet." },
            { "They.don.t.match.Try.again", "De matchar inte. F\u00F6rs\u00F6k igen" },
            { "This.extension.cannot.be.marked.as.critical.", "Detta till\u00E4gg kan inte markeras som kritiskt. " },
            { "Timestamp.", "Tidsst\u00E4mpel:" },
            { "Too.many.failures.Alias.not.changed", "F\u00F6r m\u00E5nga fel. Alias har inte \u00E4ndrats" },
            { "Too.many.failures.Key.entry.not.cloned", "F\u00F6r m\u00E5nga fel. Nyckelposten har inte klonats" },
            { "Too.many.failures.key.not.added.to.keystore", "F\u00F6r m\u00E5nga fel - nyckeln lades inte till i nyckellagret" },
            { "Too.many.failures.try.later", "F\u00F6r m\u00E5nga fel - f\u00F6rs\u00F6k igen senare" },
            { "Too.many.retries.program.terminated", "F\u00F6r m\u00E5nga f\u00F6rs\u00F6k. Programmet avslutas" },
            { "Top.level.certificate.in.reply.", "Toppniv\u00E5certifikatet i svaret:\n" },
            { "Trust.this.certificate.no.", "Litar du p\u00E5 det h\u00E4r certifikatet? [nej]:  " },
            { "Unknown.AccessDescription.type.", "Ok\u00E4nd AccessDescription-typ: " },
            { "Unknown.Entry.Type", "Ok\u00E4nd posttyp" },
            { "Unknown.extendedkeyUsage.type.", "Ok\u00E4nd extendedkeyUsage-typ: " },
            { "Unknown.extension.type.", "Ok\u00E4nd till\u00E4ggstyp: " },
            { "Unknown.keyUsage.type.", "Ok\u00E4nd keyUsage-typ: " },
            { "Unknown.password.type.", "Ok\u00E4nd l\u00F6senordstyp: " },
            { "Unrecognized.GeneralName.type.", "Ok\u00E4nd GeneralName-typ: " },
            { "Usage.error.no.command.provided", "Syntaxfel: inget kommando angivet" },
            { "Use.keytool.command.name.help.for.usage.of.command.name", "Anv\u00E4nd \"keytool -command_name -help\" f\u00F6r syntax f\u00F6r command_name.\nAnv\u00E4nd alternativet -conf <url> f\u00F6r att ange en f\u00F6rkonfigurerad alternativfil." },
            { "Use.keytool.help.for.all.available.commands", "L\u00E4s \"Hj\u00E4lp - Nyckelverktyg\" f\u00F6r alla tillg\u00E4ngliga kommandon" },
            { "Validity.must.be.greater.than.zero", "Giltigheten m\u00E5ste vara st\u00F6rre \u00E4n noll" },
            { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "Varning!  PKCS12-nyckellager har inte st\u00F6d f\u00F6r olika l\u00F6senord f\u00F6r lagret och nyckeln. Det anv\u00E4ndarspecificerade {0}-v\u00E4rdet ignoreras." },
            { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "Varning! Det befintliga aliaset {0} i destinationsnyckellagret skrivs \u00F6ver" },
            { "What.is.the.name.of.your.City.or.Locality.", "Vad heter din ort eller plats?" },
            { "What.is.the.name.of.your.State.or.Province.", "Vad heter ditt land eller din provins?" },
            { "What.is.the.name.of.your.organization.", "Vad heter din organisation?" },
            { "What.is.the.name.of.your.organizational.unit.", "Vad heter din avdelning inom organisationen?" },
            { "What.is.the.two.letter.country.code.for.this.unit.", "Vilken \u00E4r den tv\u00E5st\u00E4lliga landskoden?" },
            { "What.is.your.first.and.last.name.", "Vad heter du i f\u00F6r- och efternamn?" },
            { "Wrong.answer.try.again", "Fel svar. F\u00F6rs\u00F6k p\u00E5 nytt." },
            { "X.509.extension", "X.509-till\u00E4gg" },
            { "YES", "JA" },
            { "Your.keystore.contains.keyStore.size.entries", "Nyckellagret inneh\u00E5ller {0,number,integer} poster" },
            { "Your.keystore.contains.keyStore.size.entry", "Nyckellagret inneh\u00E5ller {0,number,integer} post" },
            { "access.the.cacerts.keystore", "\u00E5tkomst till nyckellagret cacerts" },
            { "addprovider.option", "l\u00E4gg till s\u00E4kerhetsleverant\u00F6r per namn (t.ex. SunPKCS11)\nkonfigurera argument f\u00F6r -addprovider" },
            { "alias.", "{0}, " },
            { "alias.has.no.X.509.certificate", "{0} saknar X.509-certifikat" },
            { "alias.has.no.public.key", "{0} saknar \u00F6ppen nyckel" },
            { "alias.has.no.public.key.certificate.", "{0} saknar \u00F6ppen nyckel (certifikat)" },
            { "alias.in.cacerts", "Utf\u00E4rdaren <%s> i cacerts" },
            { "alias.in.keystore", "Utf\u00E4rdaren <%s>" },
            { "alias.keyStore.getCreationDate.alias.", "{0}, {1,date}, " },
            { "alias.name.of.the.entry.to.process", "aliasnamn f\u00F6r post som ska bearbetas" },
            { "backup.keystore.warning", "Det ursprungliga nyckellagret, \"%1$s\", s\u00E4kerhetskopieras som \"%3$s\"..." },
            { "certificate.validity.start.date.time", "startdatum/-tid f\u00F6r certifikatets giltighet" },
            { "command.{0}.is.ambiguous.", "kommandot {0} \u00E4r tvetydigt:" },
            { "destination.alias", "destinationsalias" },
            { "destination.key.password", "l\u00F6senord f\u00F6r destinationsnyckel" },
            { "destination.keystore.name", "namn p\u00E5 destinationsnyckellager" },
            { "destination.keystore.password", "l\u00F6senord f\u00F6r destinationsnyckellager" },
            { "destination.keystore.password.protected", "skyddat l\u00F6senord f\u00F6r destinationsnyckellager" },
            { "destination.keystore.provider.name", "leverant\u00F6rsnamn f\u00F6r destinationsnyckellager" },
            { "destination.keystore.type", "typ av destinationsnyckellager" },
            { "distinguished.name", "unikt namn" },
            { "do.not.prompt", "fr\u00E5ga inte" },
            { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "om alias inte angivits ska inte heller destalias och srckeypass anges" },
            { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "om nyckellagret inte \u00E4r l\u00F6senordsskyddat f\u00E5r -storepass, -keypass och -new inte anges" },
            { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "om -protected har angetts f\u00E5r inte -storepass, -keypass och -new anges" },
            { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "om k\u00E4llnyckellagret inte \u00E4r l\u00F6senordsskyddat f\u00E5r -srcstorepass och -srckeypass inte anges" },
            { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "om -srcprotected anges f\u00E5r -srcstorepass och -srckeypass inte anges" },
            { "importing.keystore.status", "Importerar nyckellagret %1$s till %2$s..." },
            { "input.file.name", "namn p\u00E5 indatafil" },
            { "jks.storetype.warning", "Nyckellagret %1$s anv\u00E4nder ett propriet\u00E4rt format. Du b\u00F6r migrera till PKCS12, som \u00E4r ett branschstandardformat, med \"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"." },
            { "key.algorithm.name", "namn p\u00E5 nyckelalgoritm" },
            { "key.bit", "%1$d-bitars %2$s-nyckel" },
            { "key.bit.size", "nyckelbitstorlek" },
            { "key.bit.weak", "%1$d-bitars %2$s-nyckel (svag)" },
            { "key.password", "nyckell\u00F6senord" },
            { "key.password.for.alias.", "nyckell\u00F6senord f\u00F6r <{0}>" },
            { "keystore.name", "namn p\u00E5 nyckellager" },
            { "keystore.password", "l\u00F6senord f\u00F6r nyckellager" },
            { "keystore.type", "nyckellagertyp" },
            { "keytool.error.", "nyckelverktygsfel: " },
            { "migrate.keystore.warning", "Migrerade \"%1$s\" till %4$s. Nyckellagret %2$s s\u00E4kerhetskopierades som \"%3$s\"." },
            { "multiple.commands.1.2", "Endast ett kommando \u00E4r till\u00E5tet: du har angett b\u00E5de %1$s och %2$s." },
            { "n", "n" },
            { "new.password", "nytt l\u00F6senord" },
            { "no", "nej" },
            { "one.in.many", "%1$s #%2$d av %3$d" },
            { "option.1.set.twice", "Du har angett alternativet %s flera g\u00E5nger. Alla f\u00F6rutom det sista ignoreras." },
            { "output.file.name", "namn p\u00E5 utdatafil" },
            { "output.in.RFC.style", "utdata i RFC-format" },
            { "password.through.protected.mechanism", "l\u00F6senord med skyddad mekanism" },
            { "provclass.not.a.provider", "%s \u00E4r inte en leverant\u00F6r" },
            { "provider.class.not.found", "Leverant\u00F6ren \"%s\" hittades inte" },
            { "provider.class.option", "l\u00E4gg till s\u00E4kerhetsleverant\u00F6r per fullt kvalificerat klassnamn\nkonfigurera argument f\u00F6r -providerclass" },
            { "provider.classpath", "leverant\u00F6rsklass\u00F6kv\u00E4g" },
            { "provider.name", "leverant\u00F6rsnamn" },
            { "provider.name.not.found", "Leverant\u00F6ren med namnet \"%s\" hittades inte" },
            { "reply", "Svar" },
            { "signature.algorithm.name", "namn p\u00E5 signaturalgoritm" },
            { "signed.jar.file", "signerad jar-fil" },
            { "source.alias", "k\u00E4llalias" },
            { "source.key.password", "l\u00F6senord f\u00F6r k\u00E4llnyckel" },
            { "source.keystore.name", "namn p\u00E5 k\u00E4llnyckellager" },
            { "source.keystore.password", "l\u00F6senord f\u00F6r k\u00E4llnyckellager" },
            { "source.keystore.password.protected", "skyddat l\u00F6senord f\u00F6r k\u00E4llnyckellager" },
            { "source.keystore.provider.name", "leverant\u00F6rsnamn f\u00F6r k\u00E4llnyckellager" },
            { "source.keystore.type", "typ av k\u00E4llnyckellager" },
            { "the.certificate", "Certifikatet" },
            { "the.certificate.request", "Certifikatbeg\u00E4ran" },
            { "the.crl", "Listan \u00F6ver \u00E5terkallade certifikat" },
            { "the.generated.certificate", "Det genererade certifikatet" },
            { "the.generated.certificate.request", "Den genererade certifikatbeg\u00E4ran" },
            { "the.generated.crl", "Den genererade listan \u00F6ver \u00E5terkallade certifikat" },
            { "the.input", "Indata" },
            { "the.issuer", "Utf\u00E4rdaren" },
            { "the.keystore.or.storetype.option.cannot.be.used.with.the.cacerts.option", "Alternativen -keystore och -storetype kan inte anv\u00E4ndas med alternativet -cacerts" },
            { "the.tsa.certificate", "TSA-certifikatet" },
            { "trust.certificates.from.cacerts", "tillf\u00F6rlitliga certifikat fr\u00E5n cacerts" },
            { "unknown.size.1", "ok\u00E4nd storlek p\u00E5 nyckeln %s" },
            { "validity.number.of.days", "antal dagar f\u00F6r giltighet" },
            { "verbose.output", "utf\u00F6rliga utdata" },
            { "verified.by.s.in.s.weak", "Verifierades av %1$s i %2$s med en %3$s" },
            { "warning.cacerts.option", "Varning: anv\u00E4nd alternativet -cacerts f\u00F6r att f\u00E5 \u00E5tkomst till nyckellagret cacerts" },
            { "warning.not.verified.make.sure.keystore.is.correct", "VARNING: ej verifierad. Se till att -nyckellager \u00E4r korrekt." },
            { "whose.key.risk", "%1$s anv\u00E4nder en %2$s, vilket anses utg\u00F6ra en s\u00E4kerhetsrisk." },
            { "whose.sigalg.risk", "%1$s anv\u00E4nder signaturalgoritmen %2$s, vilket anses utg\u00F6ra en s\u00E4kerhetsrisk." },
            { "with.weak", "%s (svag)" },
            { "y", "j" },
            { "yes", "ja" },
        };
    }
}
