package sun.security.tools.keytool.resources;

import java.util.ListResourceBundle;

public final class keytool_fr extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Empty.value.", "(Valeur vide)" },
            { ".OPTION.", " [OPTION]..." },
            { ".PATTERN.printX509Cert.with.weak", "Propri\u00E9taire : {0}\nEmetteur : {1}\nNum\u00E9ro de s\u00E9rie : {2}\nValide du {3} au {4}\nEmpreintes du certificat :\n\t SHA 1: {5}\n\t SHA 256: {6}\nNom de l''algorithme de signature : {7}\nAlgorithme de cl\u00E9 publique du sujet : {8}\nVersion : {9}" },
            { ".RETURN.if.same.as.for.otherAlias.", "\t(appuyez sur Entr\u00E9e si le r\u00E9sultat est identique \u00E0 <{0}>)" },
            { ".RETURN.if.same.as.keystore.password.", "\t(appuyez sur Entr\u00E9e s'il s'agit du mot de passe du fichier de cl\u00E9s) :  " },
            { ".Storing.ksfname.", "[Stockage de {0}]" },
            { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "* L'int\u00E9grit\u00E9 des informations stock\u00E9es dans le fichier de cl\u00E9s source  *\n* n'a PAS \u00E9t\u00E9 v\u00E9rifi\u00E9e. Pour cela, *\n* vous devez fournir le mot de passe de votre fichier de cl\u00E9s source.                  *" },
            { ".The.integrity.of.the.information.stored.in.your.keystore.", "* L'int\u00E9grit\u00E9 des informations stock\u00E9es dans votre fichier de cl\u00E9s  *\n* n'a PAS \u00E9t\u00E9 v\u00E9rifi\u00E9e. Pour cela, *\n* vous devez fournir le mot de passe de votre fichier de cl\u00E9s.                  *" },
            { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" },
            { ".defaultValue.", "  [{0}]:  " },
            { ".is.not.trusted.", "... non s\u00E9curis\u00E9. " },
            { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "Les commandes -keypass et -new ne peuvent pas \u00EAtre sp\u00E9cifi\u00E9es si -storetype est d\u00E9fini sur {0}" },
            { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "Les commandes -keypasswd ne sont pas prises en charge si -storetype est d\u00E9fini sur PKCS12" },
            { ".keystore.must.be.NONE.if.storetype.is.{0}", "-keystore doit \u00EAtre d\u00E9fini sur NONE si -storetype est {0}" },
            { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "Les commandes -storepasswd et -keypasswd ne sont pas prises en charge si -storetype est d\u00E9fini sur {0}" },
            { "Alias.alias.does.not.exist", "L''alias <{0}> n''existe pas" },
            { "Alias.alias.has.no.certificate", "L''alias <{0}> ne poss\u00E8de pas de certificat" },
            { "Alias.alias.has.no.key", "L''alias <{0}> n''est associ\u00E9 \u00E0 aucune cl\u00E9" },
            { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "L''entr\u00E9e \u00E0 laquelle l''alias <{0}> fait r\u00E9f\u00E9rence n''est pas une entr\u00E9e de type cl\u00E9 priv\u00E9e. La commande -keyclone prend uniquement en charge le clonage des cl\u00E9s priv\u00E9es" },
            { "Alias.name.alias", "Nom d''alias : {0}" },
            { "CRLs.", "Listes des certificats r\u00E9voqu\u00E9s (CRL) :" },
            { "Cannot.derive.signature.algorithm", "Impossible de d\u00E9duire l'algorithme de signature" },
            { "Cannot.find.environment.variable.", "Variable d'environnement introuvable : " },
            { "Cannot.find.file.", "Fichier introuvable : " },
            { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "Le certificat existe d\u00E9j\u00E0 dans le fichier de cl\u00E9s d''acc\u00E8s sous l''alias <{0}>" },
            { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "Le certificat existe d\u00E9j\u00E0 dans le fichier de cl\u00E9s d''acc\u00E8s CA syst\u00E8me sous l''alias <{0}>" },
            { "Certificate.chain.in.reply.does.not.verify.", "La cha\u00EEne de certificat de la r\u00E9ponse ne concorde pas : " },
            { "Certificate.chain.length.", "Longueur de cha\u00EEne du certificat : " },
            { "Certificate.fingerprint.SHA.256.", "Empreinte du certificat (SHA-256) : " },
            { "Certificate.i.1.", "Certificat[{0,number,integer}]:" },
            { "Certificate.not.imported.alias.alias.already.exists", "Certificat non import\u00E9, l''alias <{0}> existe d\u00E9j\u00E0" },
            { "Certificate.owner.", "Propri\u00E9taire du certificat : " },
            { "Certificate.reply.and.certificate.in.keystore.are.identical", "La r\u00E9ponse au certificat et le certificat du fichier de cl\u00E9s sont identiques" },
            { "Certificate.reply.does.not.contain.public.key.for.alias.", "La r\u00E9ponse au certificat ne contient pas de cl\u00E9 publique pour <{0}>" },
            { "Certificate.reply.was.installed.in.keystore", "R\u00E9ponse de certificat install\u00E9e dans le fichier de cl\u00E9s" },
            { "Certificate.reply.was.not.installed.in.keystore", "R\u00E9ponse de certificat non install\u00E9e dans le fichier de cl\u00E9s" },
            { "Certificate.stored.in.file.filename.", "Certificat stock\u00E9 dans le fichier <{0}>" },
            { "Certificate.was.added.to.keystore", "Certificat ajout\u00E9 au fichier de cl\u00E9s" },
            { "Certificate.was.not.added.to.keystore", "Certificat non ajout\u00E9 au fichier de cl\u00E9s" },
            { "Certification.request.stored.in.file.filename.", "Demande de certification stock\u00E9e dans le fichier <{0}>" },
            { "Changes.an.entry.s.alias", "Modifie l'alias d'une entr\u00E9e" },
            { "Changes.the.key.password.of.an.entry", "Modifie le mot de passe de cl\u00E9 d'une entr\u00E9e" },
            { "Changes.the.store.password.of.a.keystore", "Modifie le mot de passe de banque d'un fichier de cl\u00E9s" },
            { "Clones.a.key.entry", "Clone une entr\u00E9e de cl\u00E9" },
            { "Command.option.flag.needs.an.argument.", "L''option de commande {0} requiert un argument." },
            { "Commands.", "Commandes :" },
            { "Creating.keystore.entry.for.id.getName.", "Cr\u00E9ation d''une entr\u00E9e de fichier de cl\u00E9s d''acc\u00E8s pour <{0}>..." },
            { "Creation.date.keyStore.getCreationDate.alias.", "Date de cr\u00E9ation : {0,date}" },
            { "Deletes.an.entry", "Supprime une entr\u00E9e" },
            { "Destination.alias.dest.already.exists", "L''alias de la destination <{0}> existe d\u00E9j\u00E0" },
            { "Do.you.still.want.to.add.it.no.", "Voulez-vous toujours l'ajouter ? [non] :  " },
            { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "Voulez-vous toujours l'ajouter \u00E0 votre fichier de cl\u00E9s ? [non] :  " },
            { "Empty.input", "Entr\u00E9e vide" },
            { "Enter.alias.name.", "Indiquez le nom d'alias :  " },
            { "Enter.destination.keystore.password.", "Entrez le mot de passe du fichier de cl\u00E9s de destination\u00A0:  " },
            { "Enter.key.password.for.alias.", "Entrez le mot de passe de la cl\u00E9 pour <{0}>" },
            { "Enter.keystore.password.", "Entrez le mot de passe du fichier de cl\u00E9s :  " },
            { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "Saisissez le nom du nouvel alias\t(ou appuyez sur Entr\u00E9e pour annuler l'import de cette entr\u00E9e)\u00A0:  " },
            { "Enter.prompt.alias.name.", "Indiquez le nom d''alias {0} :  " },
            { "Enter.source.keystore.password.", "Entrez le mot de passe du fichier de cl\u00E9s source\u00A0:  " },
            { "Enter.the.password.to.be.stored.", "Saisissez le mot de passe \u00E0 stocker :  " },
            { "Entry.for.alias.alias.not.imported.", "L''entr\u00E9e de l''alias {0} n''a pas \u00E9t\u00E9 import\u00E9e." },
            { "Entry.for.alias.alias.successfully.imported.", "L''entr\u00E9e de l''alias {0} a \u00E9t\u00E9 import\u00E9e." },
            { "Entry.type.type.", "Type d''entr\u00E9e\u00A0: {0}" },
            { "Existing.entry.alias.alias.exists.overwrite.no.", "L''alias d''entr\u00E9e {0} existe d\u00E9j\u00E0. Voulez-vous le remplacer ? [non]\u00A0:  " },
            { "Exports.certificate", "Exporte le certificat" },
            { "Extension.Request.", "Demande d'extension :" },
            { "Extensions.", "Extensions\u00A0: " },
            { "Failed.to.establish.chain.from.reply", "Impossible de cr\u00E9er une cha\u00EEne \u00E0 partir de la r\u00E9ponse" },
            { "Failed.to.parse.input", "L'analyse de l'entr\u00E9e a \u00E9chou\u00E9" },
            { "Generated.keyAlgName.secret.key", "Cl\u00E9 secr\u00E8te {0} g\u00E9n\u00E9r\u00E9e" },
            { "Generated.keysize.bit.keyAlgName.secret.key", "Cl\u00E9 secr\u00E8te {0} bits {1} g\u00E9n\u00E9r\u00E9e" },
            { "Generates.CRL", "G\u00E9n\u00E8re la liste des certificats r\u00E9voqu\u00E9s (CRL)" },
            { "Generates.a.certificate.request", "G\u00E9n\u00E8re une demande de certificat" },
            { "Generates.a.key.pair", "G\u00E9n\u00E8re une paire de cl\u00E9s" },
            { "Generates.a.secret.key", "G\u00E9n\u00E8re une cl\u00E9 secr\u00E8te" },
            { "Generates.a.self.signed.certificate", "G\u00E9n\u00E8re un certificat auto-sign\u00E9" },
            { "Generates.certificate.from.a.certificate.request", "G\u00E9n\u00E8re le certificat \u00E0 partir d'une demande de certificat" },
            { "Generating.keysize.bit.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.validality.days.for", "G\u00E9n\u00E9ration d''une paire de cl\u00E9s {1} de {0} bits et d''un certificat auto-sign\u00E9 ({2}) d''une validit\u00E9 de {3} jours\n\tpour : {4}" },
            { "Illegal.option.", "Option non admise :  " },
            { "Illegal.startdate.value", "Valeur de date de d\u00E9but non admise" },
            { "Illegal.value.", "Valeur non admise : " },
            { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "Commande d''import ex\u00E9cut\u00E9e\u00A0: {0} entr\u00E9es import\u00E9es, \u00E9chec ou annulation de {1} entr\u00E9es" },
            { "Imports.a.certificate.or.a.certificate.chain", "Importe un certificat ou une cha\u00EEne de certificat" },
            { "Imports.a.password", "Importe un mot de passe" },
            { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "Importe les entr\u00E9es \u00E0 partir d'une base de donn\u00E9es d'identit\u00E9s de type JDK 1.1.x" },
            { "Imports.one.or.all.entries.from.another.keystore", "Importe une entr\u00E9e ou la totalit\u00E9 des entr\u00E9es depuis un autre fichier de cl\u00E9s" },
            { "Incomplete.certificate.chain.in.reply", "Cha\u00EEne de certificat incompl\u00E8te dans la r\u00E9ponse" },
            { "Input.not.an.X.509.certificate", "L'entr\u00E9e n'est pas un certificat X.509" },
            { "Install.reply.anyway.no.", "Installer la r\u00E9ponse quand m\u00EAme ? [non] :  " },
            { "Is.name.correct.", "Est-ce {0} ?" },
            { "Key.and.Certificate.Management.Tool", "Outil de gestion de certificats et de cl\u00E9s" },
            { "Key.pair.not.generated.alias.alias.already.exists", "Paire de cl\u00E9s non g\u00E9n\u00E9r\u00E9e, l''alias <{0}> existe d\u00E9j\u00E0" },
            { "Key.password.is.too.short.must.be.at.least.6.characters", "Le mot de passe de la cl\u00E9 est trop court : il doit comporter au moins 6 caract\u00E8res" },
            { "Key.password.must.be.at.least.6.characters", "Un mot de passe de cl\u00E9 doit comporter au moins 6 caract\u00E8res" },
            { "Keystore.entry.for.id.getName.already.exists", "L''entr\u00E9e de fichier de cl\u00E9s d''acc\u00E8s pour <{0}> existe d\u00E9j\u00E0" },
            { "Keystore.file.does.not.exist.", "Le fichier de cl\u00E9s n'existe pas : " },
            { "Keystore.file.exists.but.is.empty.", "Fichier de cl\u00E9s existant mais vide : " },
            { "Keystore.password.is.too.short.must.be.at.least.6.characters", "Le mot de passe du fichier de cl\u00E9s est trop court : il doit comporter au moins 6 caract\u00E8res" },
            { "Keystore.password.must.be.at.least.6.characters", "Un mot de passe de fichier de cl\u00E9s doit comporter au moins 6 caract\u00E8res" },
            { "Keystore.provider.", "Fournisseur de fichier de cl\u00E9s : " },
            { "Keystore.type.", "Type de fichier de cl\u00E9s : " },
            { "Lists.entries.in.a.keystore", "R\u00E9pertorie les entr\u00E9es d'un fichier de cl\u00E9s" },
            { "Must.not.specify.both.v.and.rfc.with.list.command", "-v et -rfc ne doivent pas \u00EAtre sp\u00E9cifi\u00E9s avec la commande 'list'" },
            { "Must.specify.alias", "L'alias doit \u00EAtre sp\u00E9cifi\u00E9" },
            { "Must.specify.destination.alias", "L'alias de destination doit \u00EAtre sp\u00E9cifi\u00E9" },
            { "NEWLINE", "\n" },
            { "NO", "NON" },
            { "New.certificate.self.signed.", "Nouveau certificat (auto-sign\u00E9) :" },
            { "New.password.must.be.at.least.6.characters", "Le nouveau mot de passe doit comporter au moins 6 caract\u00E8res" },
            { "New.prompt.", "Nouveau {0} : " },
            { "No.certificate.from.the.SSL.server", "Aucun certificat du serveur SSL" },
            { "No.entries.from.identity.database.added", "Aucune entr\u00E9e ajout\u00E9e \u00E0 partir de la base de donn\u00E9es d'identit\u00E9s" },
            { "Not.X.509.certificate", "Pas un certificat X.509" },
            { "Not.a.signed.jar.file", "Fichier JAR non sign\u00E9" },
            { "Odd.number.of.hex.digits.found.", "Nombre impair de chiffres hexad\u00E9cimaux trouv\u00E9 : " },
            { "Options.", "Options :" },
            { "PKCS.10.with.weak", "Demande de certificat PKCS #10 (version 1.0)\nSujet : %1$s\nFormat : %2$s\nCl\u00E9 publique : %3$s\nAlgorithme de signature : %4$s\n" },
            { "Password.is.too.short.must.be.at.least.6.characters", "Le mot de passe est trop court : il doit comporter au moins 6 caract\u00E8res" },
            { "Passwords.must.differ", "Les mots de passe doivent diff\u00E9rer" },
            { "Please.provide.keysize.for.secret.key.generation", "Indiquez -keysize pour la g\u00E9n\u00E9ration de la cl\u00E9 secr\u00E8te" },
            { "Please.specify.srckeystore", "Indiquez -srckeystore" },
            { "Prints.the.content.of.a.CRL.file", "Imprime le contenu d'un fichier de liste des certificats r\u00E9voqu\u00E9s (CRL)" },
            { "Prints.the.content.of.a.certificate", "Imprime le contenu d'un certificat" },
            { "Prints.the.content.of.a.certificate.request", "Imprime le contenu d'une demande de certificat" },
            { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "Probl\u00E8me lors de l''import de l''entr\u00E9e de l''alias {0}\u00A0: {1}.\nL''entr\u00E9e de l''alias {0} n''a pas \u00E9t\u00E9 import\u00E9e." },
            { "Public.keys.in.reply.and.keystore.don.t.match", "Les cl\u00E9s publiques de la r\u00E9ponse et du fichier de cl\u00E9s ne concordent pas" },
            { "Re.enter.new.password.", "Ressaisissez le nouveau mot de passe : " },
            { "Re.enter.new.prompt.", "Indiquez encore le nouveau {0} : " },
            { "Re.enter.password.", "R\u00E9p\u00E9tez le mot de passe : " },
            { "Reply.has.no.certificates", "La r\u00E9ponse n'a pas de certificat" },
            { "SSL.server.host.and.port", "Port et h\u00F4te du serveur SSL" },
            { "STAR", "*******************************************" },
            { "STARNN", "*******************************************\n\n" },
            { "Secret.key.not.generated.alias.alias.already.exists", "Cl\u00E9 secr\u00E8te non g\u00E9n\u00E9r\u00E9e, l''alias <{0}> existe d\u00E9j\u00E0" },
            { "Serial.ID.of.cert.to.revoke", "ID de s\u00E9rie du certificat \u00E0 r\u00E9voquer" },
            { "Signature.", "Signature :" },
            { "Signer.d.", "Signataire n\u00B0%d :" },
            { "Source.keystore.file.exists.but.is.empty.", "Le fichier de cl\u00E9s source existe mais il est vide : " },
            { "Submit.this.to.your.CA", "Soumettre \u00E0 votre CA" },
            { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "Le fichier de cl\u00E9s pkcs12 de destination contient un mot de passe de fichier de cl\u00E9s et un mot de passe de cl\u00E9 diff\u00E9rents. R\u00E9essayez en sp\u00E9cifiant -destkeypass." },
            { "They.don.t.match.Try.again", "Ils sont diff\u00E9rents. R\u00E9essayez." },
            { "This.extension.cannot.be.marked.as.critical.", "Cette extension ne peut pas \u00EAtre marqu\u00E9e comme critique. " },
            { "Timestamp.", "Horodatage :" },
            { "Too.many.failures.Alias.not.changed", "Trop d'erreurs. Alias non modifi\u00E9" },
            { "Too.many.failures.Key.entry.not.cloned", "Trop d'erreurs. Entr\u00E9e de cl\u00E9 non clon\u00E9e" },
            { "Too.many.failures.key.not.added.to.keystore", "Trop d'erreurs. Cl\u00E9 non ajout\u00E9e au fichier de cl\u00E9s" },
            { "Too.many.failures.try.later", "Trop d'erreurs. R\u00E9essayez plus tard" },
            { "Too.many.retries.program.terminated", "Trop de tentatives, fin du programme" },
            { "Top.level.certificate.in.reply.", "Certificat de niveau sup\u00E9rieur dans la r\u00E9ponse :\n" },
            { "Trust.this.certificate.no.", "Faire confiance \u00E0 ce certificat ? [non] :  " },
            { "Unknown.AccessDescription.type.", "Type AccessDescription inconnu : " },
            { "Unknown.Entry.Type", "Type d'entr\u00E9e inconnu" },
            { "Unknown.extendedkeyUsage.type.", "Type extendedkeyUsage inconnu : " },
            { "Unknown.extension.type.", "Type d'extension inconnu : " },
            { "Unknown.keyUsage.type.", "Type keyUsage inconnu : " },
            { "Unknown.password.type.", "Type de mot de passe inconnu : " },
            { "Unrecognized.GeneralName.type.", "Type GeneralName non reconnu : " },
            { "Usage.error.no.command.provided", "Erreur de syntaxe\u00A0: aucune commande fournie" },
            { "Use.keytool.command.name.help.for.usage.of.command.name", "Utilisez \"keytool -command_name -help\" pour la syntaxe de command_name.\nUtilisez l'option -conf <url> pour indiquer un fichier d'options pr\u00E9configur\u00E9es." },
            { "Use.keytool.help.for.all.available.commands", "Utiliser \"keytool -help\" pour toutes les commandes disponibles" },
            { "Validity.must.be.greater.than.zero", "La validit\u00E9 doit \u00EAtre sup\u00E9rieure \u00E0 z\u00E9ro" },
            { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "Avertissement\u00A0: les mots de passe de cl\u00E9 et de banque distincts ne sont pas pris en charge pour les fichiers de cl\u00E9s d''acc\u00E8s PKCS12. La valeur {0} sp\u00E9cifi\u00E9e par l''utilisateur est ignor\u00E9e." },
            { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "Avertissement\u00A0: l''alias {0} existant sera remplac\u00E9 dans le fichier de cl\u00E9s d''acc\u00E8s de destination" },
            { "What.is.the.name.of.your.City.or.Locality.", "Quel est le nom de votre ville de r\u00E9sidence ?" },
            { "What.is.the.name.of.your.State.or.Province.", "Quel est le nom de votre \u00E9tat ou province ?" },
            { "What.is.the.name.of.your.organization.", "Quel est le nom de votre entreprise ?" },
            { "What.is.the.name.of.your.organizational.unit.", "Quel est le nom de votre unit\u00E9 organisationnelle ?" },
            { "What.is.the.two.letter.country.code.for.this.unit.", "Quel est le code pays \u00E0 deux lettres pour cette unit\u00E9 ?" },
            { "What.is.your.first.and.last.name.", "Quels sont vos nom et pr\u00E9nom ?" },
            { "Wrong.answer.try.again", "R\u00E9ponse incorrecte, recommencez" },
            { "X.509.extension", "extension X.509" },
            { "YES", "OUI" },
            { "Your.keystore.contains.keyStore.size.entries", "Votre fichier de cl\u00E9s d''acc\u00E8s contient {0,number,integer} entr\u00E9es" },
            { "Your.keystore.contains.keyStore.size.entry", "Votre fichier de cl\u00E9s d''acc\u00E8s contient {0,number,integer} entr\u00E9e" },
            { "access.the.cacerts.keystore", "acc\u00E9der au fichier de cl\u00E9s cacerts" },
            { "addprovider.option", "ajouter un fournisseur de s\u00E9curit\u00E9 par nom (par ex. SunPKCS11)\nconfigurer l'argument pour -addprovider" },
            { "alias.", "{0}, " },
            { "alias.has.no.X.509.certificate", "{0} ne poss\u00E8de pas de certificat X.509" },
            { "alias.has.no.public.key", "{0} ne poss\u00E8de pas de cl\u00E9 publique" },
            { "alias.has.no.public.key.certificate.", "{0} ne poss\u00E8de pas de cl\u00E9 publique (certificat)" },
            { "alias.in.cacerts", "Emetteur <%s> dans les certificats CA" },
            { "alias.in.keystore", "Emetteur <%s>" },
            { "alias.keyStore.getCreationDate.alias.", "{0}, {1,date}, " },
            { "alias.name.of.the.entry.to.process", "nom d'alias de l'entr\u00E9e \u00E0 traiter" },
            { "backup.keystore.warning", "Le fichier de cl\u00E9s d'origine \"%1$s\" est sauvegard\u00E9 en tant que \"%3$s\"..." },
            { "certificate.validity.start.date.time", "date/heure de d\u00E9but de validit\u00E9 du certificat" },
            { "command.{0}.is.ambiguous.", "commande {0} ambigu\u00EB :" },
            { "destination.alias", "alias de destination" },
            { "destination.key.password", "mot de passe de la cl\u00E9 de destination" },
            { "destination.keystore.name", "nom du fichier de cl\u00E9s de destination" },
            { "destination.keystore.password", "mot de passe du fichier de cl\u00E9s de destination" },
            { "destination.keystore.password.protected", "mot de passe du fichier de cl\u00E9s de destination prot\u00E9g\u00E9" },
            { "destination.keystore.provider.name", "nom du fournisseur du fichier de cl\u00E9s de destination" },
            { "destination.keystore.type", "type du fichier de cl\u00E9s de destination" },
            { "distinguished.name", "nom distinctif" },
            { "do.not.prompt", "ne pas inviter" },
            { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "si l'alias n'est pas sp\u00E9cifi\u00E9, destalias et srckeypass ne doivent pas \u00EAtre sp\u00E9cifi\u00E9s" },
            { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "Si le fichier de cl\u00E9s n'est pas prot\u00E9g\u00E9 par un mot de passe, les commandes -storepass, -keypass et -new ne doivent pas \u00EAtre sp\u00E9cifi\u00E9es" },
            { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "si -protected est sp\u00E9cifi\u00E9, -storepass, -keypass et -new ne doivent pas \u00EAtre indiqu\u00E9s" },
            { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "Si le fichier de cl\u00E9s source n'est pas prot\u00E9g\u00E9 par un mot de passe, les commandes -srcstorepass et -srckeypass ne doivent pas \u00EAtre sp\u00E9cifi\u00E9es" },
            { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "Si -srcprotected est indiqu\u00E9, les commandes -srcstorepass et -srckeypass ne doivent pas \u00EAtre sp\u00E9cifi\u00E9es" },
            { "importing.keystore.status", "Import du fichier de cl\u00E9s %1$s vers %2$s..." },
            { "input.file.name", "nom du fichier d'entr\u00E9e" },
            { "jks.storetype.warning", "Le fichier de cl\u00E9s %1$s utilise un format propri\u00E9taire. Il est recommand\u00E9 de migrer vers PKCS12, qui est un format standard de l'industrie en utilisant \"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"." },
            { "key.algorithm.name", "nom de l'algorithme de cl\u00E9" },
            { "key.bit", "Cl\u00E9 %2$s %1$d bits" },
            { "key.bit.size", "taille en bits de la cl\u00E9" },
            { "key.bit.weak", "Cl\u00E9 %2$s %1$d bits (faible)" },
            { "key.password", "mot de passe de la cl\u00E9" },
            { "key.password.for.alias.", "mot de passe de cl\u00E9 pour <{0}>" },
            { "keystore.name", "nom du fichier de cl\u00E9s" },
            { "keystore.password", "mot de passe du fichier de cl\u00E9s" },
            { "keystore.type", "type du fichier de cl\u00E9s" },
            { "keytool.error.", "erreur keytool : " },
            { "migrate.keystore.warning", "El\u00E9ment \"%1$s\" migr\u00E9 vers %4$s. Le fichier de cl\u00E9s %2$s est sauvegard\u00E9 en tant que \"%3$s\"." },
            { "multiple.commands.1.2", "Une seule commande est autoris\u00E9e : %1$s et %2$s ont \u00E9t\u00E9 sp\u00E9cifi\u00E9es." },
            { "n", "n" },
            { "new.password", "nouveau mot de passe" },
            { "no", "non" },
            { "one.in.many", "%1$s #%2$d sur %3$d" },
            { "option.1.set.twice", "L'option %s est sp\u00E9cifi\u00E9e plusieurs fois. Toutes les occurrences seront ignor\u00E9es, sauf la derni\u00E8re." },
            { "output.file.name", "nom du fichier de sortie" },
            { "output.in.RFC.style", "sortie au style RFC" },
            { "password.through.protected.mechanism", "mot de passe via m\u00E9canisme prot\u00E9g\u00E9" },
            { "provclass.not.a.provider", "%s n'est pas un fournisseur" },
            { "provider.class.not.found", "Fournisseur \"%s\" introuvable" },
            { "provider.class.option", "ajouter un fournisseur de s\u00E9curit\u00E9 par nom de classe qualifi\u00E9 complet\nconfigurer l'argument pour -providerclass" },
            { "provider.classpath", "variable d'environnement CLASSPATH du fournisseur" },
            { "provider.name", "nom du fournisseur" },
            { "provider.name.not.found", "Fournisseur nomm\u00E9 \"%s\" introuvable" },
            { "reply", "R\u00E9pondre" },
            { "signature.algorithm.name", "nom de l'algorithme de signature" },
            { "signed.jar.file", "fichier JAR sign\u00E9" },
            { "source.alias", "alias source" },
            { "source.key.password", "mot de passe de la cl\u00E9 source" },
            { "source.keystore.name", "nom du fichier de cl\u00E9s source" },
            { "source.keystore.password", "mot de passe du fichier de cl\u00E9s source" },
            { "source.keystore.password.protected", "mot de passe du fichier de cl\u00E9s source prot\u00E9g\u00E9" },
            { "source.keystore.provider.name", "nom du fournisseur du fichier de cl\u00E9s source" },
            { "source.keystore.type", "type du fichier de cl\u00E9s source" },
            { "the.certificate", "Certificat" },
            { "the.certificate.request", "Demande de certificat" },
            { "the.crl", "Liste de certificats r\u00E9voqu\u00E9s" },
            { "the.generated.certificate", "Certificat g\u00E9n\u00E9r\u00E9" },
            { "the.generated.certificate.request", "Demande de certificat g\u00E9n\u00E9r\u00E9" },
            { "the.generated.crl", "Liste des certificats r\u00E9voqu\u00E9s g\u00E9n\u00E9r\u00E9e" },
            { "the.input", "Entr\u00E9e" },
            { "the.issuer", "Emetteur" },
            { "the.keystore.or.storetype.option.cannot.be.used.with.the.cacerts.option", "Les options -keystore ou -storetype ne peuvent pas \u00EAtre utilis\u00E9es avec l'option -cacerts" },
            { "the.tsa.certificate", "Certificat TSA" },
            { "trust.certificates.from.cacerts", "certificats s\u00E9curis\u00E9s issus de certificats CA" },
            { "unknown.size.1", "taille de cl\u00E9 %s inconnue" },
            { "validity.number.of.days", "nombre de jours de validit\u00E9" },
            { "verbose.output", "sortie en mode verbose" },
            { "verified.by.s.in.s.weak", "V\u00E9rifi\u00E9 par %1$s dans %2$s avec un \u00E9l\u00E9ment %3$s" },
            { "warning.cacerts.option", "Avertissement : utiliser l'option -cacerts pour acc\u00E9der au fichier de cl\u00E9s cacerts" },
            { "warning.not.verified.make.sure.keystore.is.correct", "AVERTISSEMENT : non v\u00E9rifi\u00E9. Assurez-vous que -keystore est correct." },
            { "whose.key.risk", "%1$s utilise un \u00E9l\u00E9ment %2$s, qui repr\u00E9sente un risque pour la s\u00E9curit\u00E9." },
            { "whose.sigalg.risk", "%1$s utilise l'algorithme de signature %2$s, qui repr\u00E9sente un risque pour la s\u00E9curit\u00E9." },
            { "with.weak", "%s (faible)" },
            { "y", "o" },
            { "yes", "oui" },
        };
    }
}
