package sun.security.tools.keytool.resources;

import java.util.ListResourceBundle;

public final class keytool_it extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Empty.value.", "(valore vuoto)" },
            { ".OPTION.", " [OPTION]..." },
            { ".PATTERN.printX509Cert.with.weak", "Proprietario: {0}\nEmittente: {1}\nNumero di serie: {2}\nValido da: {3} a: {4}\nImpronte digitali certificato:\n\t SHA1: {5}\n\t SHA256: {6}\nNome algoritmo firma: {7}\nAlgoritmo di chiave pubblica oggetto: {8}\nVersione: {9}" },
            { ".RETURN.if.same.as.for.otherAlias.", "\t(INVIO se corrisponde al nome di <{0}>)" },
            { ".RETURN.if.same.as.keystore.password.", "\t(INVIO se corrisponde alla password del keystore):  " },
            { ".Storing.ksfname.", "[Memorizzazione di {0}] in corso" },
            { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "* L'integrit\u00E0 delle informazioni memorizzate nel srckeystore *\n* NON \u00E8 stata verificata. Per verificarne l'integrit\u00E0 *\n* \u00E8 necessario fornire la password del srckeystore.                  *" },
            { ".The.integrity.of.the.information.stored.in.your.keystore.", "* L'integrit\u00E0 delle informazioni memorizzate nel keystore *\n* NON \u00E8 stata verificata. Per verificarne l'integrit\u00E0 *\n* \u00E8 necessario fornire la password del keystore.                  *" },
            { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" },
            { ".defaultValue.", "  [{0}]:  " },
            { ".is.not.trusted.", "...non \u00E8 considerato sicuro. " },
            { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "Se -storetype \u00E8 impostato su {0}, non \u00E8 possibile specificare un valore per -keypass e -new" },
            { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "Se -storetype \u00E8 impostato su PKCS12 i comandi -keypasswd non vengono supportati" },
            { ".keystore.must.be.NONE.if.storetype.is.{0}", "Se -storetype \u00E8 impostato su {0}, -keystore deve essere impostato su NONE" },
            { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "Se -storetype \u00E8 impostato su {0}, i comandi -storepasswd e -keypasswd non sono supportati" },
            { "Alias.alias.does.not.exist", "L''alias <{0}> non esiste" },
            { "Alias.alias.has.no.certificate", "L''alias <{0}> non dispone di certificato" },
            { "Alias.alias.has.no.key", "All''alias <{0}> non \u00E8 associata alcuna chiave" },
            { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "L''alias <{0}> fa riferimento a un tipo di voce che non \u00E8 una voce di chiave privata. Il comando -keyclone supporta solo la copia delle voci di chiave private." },
            { "Alias.name.alias", "Nome alias: {0}" },
            { "CRLs.", "CRL:" },
            { "Cannot.derive.signature.algorithm", "Impossibile derivare l'algoritmo di firma" },
            { "Cannot.find.environment.variable.", "Impossibile trovare la variabile di ambiente: " },
            { "Cannot.find.file.", "Impossibile trovare il file: " },
            { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "Il certificato esiste gi\u00E0 nel keystore con alias <{0}>" },
            { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "Il certificato esiste gi\u00E0 nel keystore CA con alias <{0}>" },
            { "Certificate.chain.in.reply.does.not.verify.", "La catena dei certificati nella risposta non verifica: " },
            { "Certificate.chain.length.", "Lunghezza catena certificati: " },
            { "Certificate.fingerprint.SHA.256.", "Copia di certificato (SHA-256): " },
            { "Certificate.i.1.", "Certificato[{0,number,integer}]:" },
            { "Certificate.not.imported.alias.alias.already.exists", "Impossibile importare il certificato, l''alias <{0}> \u00E8 gi\u00E0 esistente" },
            { "Certificate.owner.", "Proprietario certificato: " },
            { "Certificate.reply.and.certificate.in.keystore.are.identical", "La risposta del certificato e il certificato nel keystore sono identici" },
            { "Certificate.reply.does.not.contain.public.key.for.alias.", "La risposta del certificato non contiene la chiave pubblica per <{0}>" },
            { "Certificate.reply.was.installed.in.keystore", "La risposta del certificato \u00E8 stata installata nel keystore" },
            { "Certificate.reply.was.not.installed.in.keystore", "La risposta del certificato non \u00E8 stata installata nel keystore" },
            { "Certificate.stored.in.file.filename.", "Il certificato \u00E8 memorizzato nel file <{0}>" },
            { "Certificate.was.added.to.keystore", "Il certificato \u00E8 stato aggiunto al keystore" },
            { "Certificate.was.not.added.to.keystore", "Il certificato non \u00E8 stato aggiunto al keystore" },
            { "Certification.request.stored.in.file.filename.", "La richiesta di certificazione \u00E8 memorizzata nel file <{0}>" },
            { "Changes.an.entry.s.alias", "Modifica l'alias di una voce" },
            { "Changes.the.key.password.of.an.entry", "Modifica la password della chiave per una voce" },
            { "Changes.the.store.password.of.a.keystore", "Modifica la password di area di memorizzazione di un keystore" },
            { "Clones.a.key.entry", "Duplica una voce di chiave" },
            { "Command.option.flag.needs.an.argument.", "\u00C8 necessario specificare un argomento per l''opzione di comando {0}." },
            { "Commands.", "Comandi:" },
            { "Creating.keystore.entry.for.id.getName.", "Creazione della voce del keystore per <{0}> in corso..." },
            { "Creation.date.keyStore.getCreationDate.alias.", "Data di creazione: {0,date}" },
            { "Deletes.an.entry", "Elimina una voce" },
            { "Destination.alias.dest.already.exists", "L''alias di destinazione <{0}> \u00E8 gi\u00E0 esistente" },
            { "Do.you.still.want.to.add.it.no.", "Aggiungerlo ugualmente? [no]:  " },
            { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "Aggiungerlo al proprio keystore? [no]:  " },
            { "Empty.input", "Input vuoto" },
            { "Enter.alias.name.", "Immettere nome alias:  " },
            { "Enter.destination.keystore.password.", "Immettere la password del keystore di destinazione:  " },
            { "Enter.key.password.for.alias.", "Immettere la password della chiave per <{0}>" },
            { "Enter.keystore.password.", "Immettere la password del keystore:  " },
            { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "Immettere un nuovo nome alias\t(premere INVIO per annullare l'importazione della voce):  " },
            { "Enter.prompt.alias.name.", "Immettere nome alias {0}:  " },
            { "Enter.source.keystore.password.", "Immettere la password del keystore di origine:  " },
            { "Enter.the.password.to.be.stored.", "Immettere la password da memorizzare:  " },
            { "Entry.for.alias.alias.not.imported.", "La voce dell''alias {0} non \u00E8 stata importata." },
            { "Entry.for.alias.alias.successfully.imported.", "La voce dell''alias {0} \u00E8 stata importata." },
            { "Entry.type.type.", "Tipo di voce: {0}" },
            { "Existing.entry.alias.alias.exists.overwrite.no.", "La voce dell''alias {0} esiste gi\u00E0. Sovrascrivere? [no]:  " },
            { "Exports.certificate", "Esporta il certificato" },
            { "Extension.Request.", "Richiesta di estensione:" },
            { "Extensions.", "Estensioni: " },
            { "Failed.to.establish.chain.from.reply", "Impossibile stabilire la catena dalla risposta" },
            { "Failed.to.parse.input", "Impossibile analizzare l'input" },
            { "Generated.keyAlgName.secret.key", "Generata chiave segreta {0}" },
            { "Generated.keysize.bit.keyAlgName.secret.key", "Generata chiave segreta {1} a {0} bit" },
            { "Generates.CRL", "Genera CRL" },
            { "Generates.a.certificate.request", "Genera una richiesta di certificato" },
            { "Generates.a.key.pair", "Genera una coppia di chiavi" },
            { "Generates.a.secret.key", "Genera una chiave segreta" },
            { "Generates.a.self.signed.certificate", "Genera certificato con firma automatica" },
            { "Generates.certificate.from.a.certificate.request", "Genera un certificato da una richiesta di certificato" },
            { "Generating.keysize.bit.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.validality.days.for", "Generazione in corso di una coppia di chiavi {1} da {0} bit e di un certificato autofirmato ({2}) con una validit\u00E0 di {3} giorni\n\tper: {4}" },
            { "Illegal.option.", "Opzione non valida:  " },
            { "Illegal.startdate.value", "Valore di data di inizio non valido" },
            { "Illegal.value.", "Valore non valido: " },
            { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "Comando di importazione completato: {0} voce/i importata/e, {1} voce/i non importata/e o annullata/e" },
            { "Imports.a.certificate.or.a.certificate.chain", "Importa un certificato o una catena di certificati" },
            { "Imports.a.password", "Importa una password" },
            { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "Importa le voci da un database delle identit\u00E0 di tipo JDK 1.1.x" },
            { "Imports.one.or.all.entries.from.another.keystore", "Importa una o tutte le voci da un altro keystore" },
            { "Incomplete.certificate.chain.in.reply", "Catena dei certificati incompleta nella risposta" },
            { "Input.not.an.X.509.certificate", "L'input non \u00E8 un certificato X.509" },
            { "Install.reply.anyway.no.", "Installare la risposta? [no]:  " },
            { "Is.name.correct.", "Il dato {0} \u00E8 corretto?" },
            { "Key.and.Certificate.Management.Tool", "Strumento di gestione di chiavi e certificati" },
            { "Key.pair.not.generated.alias.alias.already.exists", "Non \u00E8 stata generata la coppia di chiavi, l''alias <{0}> \u00E8 gi\u00E0 esistente" },
            { "Key.password.is.too.short.must.be.at.least.6.characters", "La password della chiave \u00E8 troppo corta - deve contenere almeno 6 caratteri" },
            { "Key.password.must.be.at.least.6.characters", "La password della chiave deve contenere almeno 6 caratteri" },
            { "Keystore.entry.for.id.getName.already.exists", "La voce del keystore per <{0}> esiste gi\u00E0" },
            { "Keystore.file.does.not.exist.", "Il file keystore non esiste: " },
            { "Keystore.file.exists.but.is.empty.", "Il file keystore esiste ma \u00E8 vuoto: " },
            { "Keystore.password.is.too.short.must.be.at.least.6.characters", "La password del keystore \u00E8 troppo corta - deve contenere almeno 6 caratteri" },
            { "Keystore.password.must.be.at.least.6.characters", "La password del keystore deve contenere almeno 6 caratteri" },
            { "Keystore.provider.", "Provider keystore: " },
            { "Keystore.type.", "Tipo keystore: " },
            { "Lists.entries.in.a.keystore", "Elenca le voci in un keystore" },
            { "Must.not.specify.both.v.and.rfc.with.list.command", "Impossibile specificare sia -v sia -rfc con il comando 'list'" },
            { "Must.specify.alias", "\u00C8 necessario specificare l'alias" },
            { "Must.specify.destination.alias", "\u00C8 necessario specificare l'alias di destinazione" },
            { "NEWLINE", "\n" },
            { "NO", "NO" },
            { "New.certificate.self.signed.", "Nuovo certificato (autofirmato):" },
            { "New.password.must.be.at.least.6.characters", "La nuova password deve contenere almeno 6 caratteri" },
            { "New.prompt.", "Nuova {0}: " },
            { "No.certificate.from.the.SSL.server", "Nessun certificato dal server SSL" },
            { "No.entries.from.identity.database.added", "Nessuna voce aggiunta dal database delle identit\u00E0" },
            { "Not.X.509.certificate", "Il certificato non \u00E8 X.509" },
            { "Not.a.signed.jar.file", "Non \u00E8 un file jar firmato" },
            { "Odd.number.of.hex.digits.found.", "\u00C8 stato trovato un numero dispari di cifre esadecimali: " },
            { "Options.", "Opzioni:" },
            { "PKCS.10.with.weak", "Richiesta di certificato PKCS #10 (versione 1.0)\nOggetto: %1$s\nFormato: %2$s\nChiave pubblica: %3$s\nAlgoritmo firma: %4$s\n" },
            { "Password.is.too.short.must.be.at.least.6.characters", "La password \u00E8 troppo corta - deve contenere almeno 6 caratteri" },
            { "Passwords.must.differ", "Le password non devono coincidere" },
            { "Please.provide.keysize.for.secret.key.generation", "Specificare il valore -keysize per la generazione della chiave segreta" },
            { "Please.specify.srckeystore", "Specificare -srckeystore" },
            { "Prints.the.content.of.a.CRL.file", "Visualizza i contenuti di un file CRL" },
            { "Prints.the.content.of.a.certificate", "Visualizza i contenuti di un certificato" },
            { "Prints.the.content.of.a.certificate.request", "Visualizza i contenuti di una richiesta di certificato" },
            { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "Si \u00E8 verificato un problema durante l''importazione della voce dell''alias {0}: {1}.\nLa voce dell''alias {0} non \u00E8 stata importata." },
            { "Public.keys.in.reply.and.keystore.don.t.match", "Le chiavi pubbliche nella risposta e nel keystore non corrispondono" },
            { "Re.enter.new.password.", "Immettere nuovamente la nuova password: " },
            { "Re.enter.new.prompt.", "Reimmettere un nuovo valore per {0}: " },
            { "Re.enter.password.", "Reimmettere la password: " },
            { "Reply.has.no.certificates", "La risposta non dispone di certificati" },
            { "SSL.server.host.and.port", "host e porta server SSL" },
            { "STAR", "*******************************************" },
            { "STARNN", "*******************************************\n\n" },
            { "Secret.key.not.generated.alias.alias.already.exists", "La chiave segreta non \u00E8 stata generata; l''alias <{0}> esiste gi\u00E0" },
            { "Serial.ID.of.cert.to.revoke", "ID seriale del certificato da revocare" },
            { "Signature.", "Firma:" },
            { "Signer.d.", "Firmatario #%d:" },
            { "Source.keystore.file.exists.but.is.empty.", "Il file keystore di origine esiste, ma \u00E8 vuoto: " },
            { "Submit.this.to.your.CA", "Sottomettere alla propria CA" },
            { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "Keystore pkcs12 di destinazione con storepass e keypass differenti. Riprovare con -destkeypass specificato." },
            { "They.don.t.match.Try.again", "Non corrispondono. Riprovare." },
            { "This.extension.cannot.be.marked.as.critical.", "Impossibile contrassegnare questa estensione come critica. " },
            { "Timestamp.", "Indicatore orario:" },
            { "Too.many.failures.Alias.not.changed", "Numero eccessivo di errori. L'alias non \u00E8 stato modificato." },
            { "Too.many.failures.Key.entry.not.cloned", "Numero eccessivo di errori. Il valore della chiave non \u00E8 stato copiato." },
            { "Too.many.failures.key.not.added.to.keystore", "Troppi errori - la chiave non \u00E8 stata aggiunta al keystore" },
            { "Too.many.failures.try.later", "Troppi errori - riprovare" },
            { "Too.many.retries.program.terminated", "Il numero dei tentativi consentiti \u00E8 stato superato. Il programma verr\u00E0 terminato." },
            { "Top.level.certificate.in.reply.", "Certificato di primo livello nella risposta:\n" },
            { "Trust.this.certificate.no.", "Considerare sicuro questo certificato? [no]:  " },
            { "Unknown.AccessDescription.type.", "Tipo AccessDescription sconosciuto: " },
            { "Unknown.Entry.Type", "Tipo di voce sconosciuto" },
            { "Unknown.extendedkeyUsage.type.", "Tipo extendedkeyUsage sconosciuto: " },
            { "Unknown.extension.type.", "Tipo di estensione sconosciuto: " },
            { "Unknown.keyUsage.type.", "Tipo keyUsage sconosciuto: " },
            { "Unknown.password.type.", "Tipo di password sconosciuto: " },
            { "Unrecognized.GeneralName.type.", "Tipo GeneralName non riconosciuto: " },
            { "Usage.error.no.command.provided", "Errore di utilizzo: nessun comando specificato" },
            { "Use.keytool.command.name.help.for.usage.of.command.name", "Utilizzare \"keytool -command_name -help\" per informazioni sull'uso di command_name.\nUtilizzare l'opzione -conf <url> per specificare un file di opzioni preconfigurato." },
            { "Use.keytool.help.for.all.available.commands", "Utilizzare \"keytool -help\" per visualizzare tutti i comandi disponibili" },
            { "Validity.must.be.greater.than.zero", "La validit\u00E0 deve essere maggiore di zero" },
            { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "Avvertenza: non sono supportate password diverse di chiave e di archivio per i keystore PKCS12. Il valore {0} specificato dall''utente verr\u00E0 ignorato." },
            { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "Avvertenza: sovrascrittura in corso dell''alias {0} nel file keystore di destinazione" },
            { "What.is.the.name.of.your.City.or.Locality.", "Specificare la localit\u00E0" },
            { "What.is.the.name.of.your.State.or.Province.", "Specificare la provincia" },
            { "What.is.the.name.of.your.organization.", "Specificare il nome dell'organizzazione" },
            { "What.is.the.name.of.your.organizational.unit.", "Specificare il nome dell'unit\u00E0 organizzativa" },
            { "What.is.the.two.letter.country.code.for.this.unit.", "Specificare il codice a due lettere del paese in cui si trova l'unit\u00E0" },
            { "What.is.your.first.and.last.name.", "Specificare nome e cognome" },
            { "Wrong.answer.try.again", "Risposta errata, riprovare" },
            { "X.509.extension", "estensione X.509" },
            { "YES", "S\u00EC" },
            { "Your.keystore.contains.keyStore.size.entries", "Il keystore contiene {0,number,integer} voci" },
            { "Your.keystore.contains.keyStore.size.entry", "Il keystore contiene {0,number,integer} voce" },
            { "access.the.cacerts.keystore", "accedi al keystore cacerts" },
            { "addprovider.option", "aggiunge il provider di sicurezza in base al nome (ad esempio SunPKCS11)\nconfigura l'argomento per -addprovider" },
            { "alias.", "{0}, " },
            { "alias.has.no.X.509.certificate", "{0} non dispone di certificato X.509" },
            { "alias.has.no.public.key", "{0} non dispone di chiave pubblica" },
            { "alias.has.no.public.key.certificate.", "{0} non dispone di chiave pubblica (certificato)" },
            { "alias.in.cacerts", "Emittente <%s> in cacerts" },
            { "alias.in.keystore", "Emittente <%s>" },
            { "alias.keyStore.getCreationDate.alias.", "{0}, {1,date}, " },
            { "alias.name.of.the.entry.to.process", "nome alias della voce da elaborare" },
            { "backup.keystore.warning", "Backup del keystore originale \"%1$s\" eseguito con il nome \"%3$s\"..." },
            { "certificate.validity.start.date.time", "data/ora di inizio validit\u00E0 certificato" },
            { "command.{0}.is.ambiguous.", "il comando {0} \u00E8 ambiguo:" },
            { "destination.alias", "alias di destinazione" },
            { "destination.key.password", "password chiave di destinazione" },
            { "destination.keystore.name", "nome keystore di destinazione" },
            { "destination.keystore.password", "password keystore di destinazione" },
            { "destination.keystore.password.protected", "password keystore di destinazione protetta" },
            { "destination.keystore.provider.name", "nome provider keystore di destinazione" },
            { "destination.keystore.type", "tipo keystore di destinazione" },
            { "distinguished.name", "nome distinto" },
            { "do.not.prompt", "non richiedere" },
            { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "Se l'alias non \u00E8 specificato, destalias e srckeypass non dovranno essere specificati" },
            { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "Se il file keystore non \u00E8 protetto da password, non deve essere specificato alcun valore per -storepass, -keypass e -new" },
            { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "Se \u00E8 specificata l'opzione -protected, le opzioni -storepass, -keypass e -new non possono essere specificate" },
            { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "Se il file keystore non \u00E8 protetto da password, non deve essere specificato alcun valore per -srcstorepass e -srckeypass" },
            { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "Se viene specificato -srcprotected, -srcstorepass e -srckeypass non dovranno essere specificati" },
            { "importing.keystore.status", "Importazione del keystore %1$s in %2$s in corso..." },
            { "input.file.name", "nome file di input" },
            { "jks.storetype.warning", "Il keystore %1$s utilizza un formato proprietario. Si consiglia di eseguire la migrazione a PKCS12, un formato standard di settore, utilizzando il comando \"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"." },
            { "key.algorithm.name", "nome algoritmo chiave" },
            { "key.bit", "Chiave %2$s a %1$d bit" },
            { "key.bit.size", "dimensione bit chiave" },
            { "key.bit.weak", "Chiave %2$s a %1$d bit (debole)" },
            { "key.password", "password chiave" },
            { "key.password.for.alias.", "password della chiave per <{0}>" },
            { "keystore.name", "nome keystore" },
            { "keystore.password", "password keystore" },
            { "keystore.type", "tipo keystore" },
            { "keytool.error.", "Errore keytool: " },
            { "migrate.keystore.warning", "Migrazione di \"%1$s\" in %4$s eseguita. Backup del keystore %2$s eseguito con il nome \"%3$s\"." },
            { "multiple.commands.1.2", "\u00C8 consentito un solo comando: \u00E8 stato specificato sia %1$s che %2$s." },
            { "n", "n" },
            { "new.password", "nuova password" },
            { "no", "no" },
            { "one.in.many", "%1$s #%2$d di %3$d" },
            { "option.1.set.twice", "L'opzione %s \u00E8 specificata pi\u00F9 volte. Tutte le ricorrenze verranno ignorate tranne l'ultima." },
            { "output.file.name", "nome file di output" },
            { "output.in.RFC.style", "output in stile RFC" },
            { "password.through.protected.mechanism", "password mediante meccanismo protetto" },
            { "provclass.not.a.provider", "%s non \u00E8 un provider" },
            { "provider.class.not.found", "Provider \"%s\" non trovato" },
            { "provider.class.option", "aggiunge il provider di sicurezza in base al nome di classe completamente qualificato\nconfigura l'argomento per -providerclass" },
            { "provider.classpath", "classpath provider" },
            { "provider.name", "nome provider" },
            { "provider.name.not.found", "Provider denominato \"%s\" non trovato" },
            { "reply", "Rispondi" },
            { "signature.algorithm.name", "nome algoritmo firma" },
            { "signed.jar.file", "file jar firmato" },
            { "source.alias", "alias origine" },
            { "source.key.password", "password chiave di origine" },
            { "source.keystore.name", "nome keystore di origine" },
            { "source.keystore.password", "password keystore di origine" },
            { "source.keystore.password.protected", "password keystore di origine protetta" },
            { "source.keystore.provider.name", "nome provider keystore di origine" },
            { "source.keystore.type", "tipo keystore di origine" },
            { "the.certificate", "Il certificato" },
            { "the.certificate.request", "La richiesta di certificato" },
            { "the.crl", "La CRL" },
            { "the.generated.certificate", "Il certificato generato" },
            { "the.generated.certificate.request", "La richiesta di certificato generata" },
            { "the.generated.crl", "La CRL generata" },
            { "the.input", "L'input" },
            { "the.issuer", "L'emittente" },
            { "the.keystore.or.storetype.option.cannot.be.used.with.the.cacerts.option", "L'opzione -keystore o -storetype non pu\u00F2 essere utilizzata con l'opzione -cacerts" },
            { "the.tsa.certificate", "Il certificato TSA" },
            { "trust.certificates.from.cacerts", "considera sicuri i certificati da cacerts" },
            { "unknown.size.1", "chiave %s di dimensione sconosciuta" },
            { "validity.number.of.days", "numero di giorni di validit\u00E0" },
            { "verbose.output", "output descrittivo" },
            { "verified.by.s.in.s.weak", "Verificato da %1$s in %2$s con un %3$s" },
            { "warning.cacerts.option", "Avvertenza: utilizzare l'opzione -cacerts per accedere al keystore cacerts" },
            { "warning.not.verified.make.sure.keystore.is.correct", "AVVERTENZA: non verificato. Assicurarsi che -keystore sia corretto." },
            { "whose.key.risk", "%1$s utilizza un %2$s che \u00E8 considerato un rischio per la sicurezza." },
            { "whose.sigalg.risk", "%1$s utilizza l'algoritmo firma %2$s che \u00E8 considerato un rischio per la sicurezza." },
            { "with.weak", "%s (debole)" },
            { "y", "s" },
            { "yes", "s\u00EC" },
        };
    }
}
