package sun.security.tools.keytool.resources;

import java.util.ListResourceBundle;

public final class keytool_es extends ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { ".Empty.value.", "(Valor vac\u00EDo)" },
            { ".OPTION.", " [OPTION]..." },
            { ".PATTERN.printX509Cert.with.weak", "Propietario: {0}\nEmisor: {1}\nN\u00FAmero de serie: {2}\nV\u00E1lido desde: {3} hasta: {4}\nHuellas digitales del certificado:\n\t SHA1: {5}\n\t SHA256: {6}\nNombre del algoritmo de firma: {7}\nAlgoritmo de clave p\u00FAblica de asunto: {8}\nVersi\u00F3n: {9}" },
            { ".RETURN.if.same.as.for.otherAlias.", "\t(INTRO si es el mismo que para <{0}>)" },
            { ".RETURN.if.same.as.keystore.password.", "\t(INTRO si es la misma contrase\u00F1a que la del almac\u00E9n de claves):  " },
            { ".Storing.ksfname.", "[Almacenando {0}]" },
            { ".The.integrity.of.the.information.stored.in.the.srckeystore.", "* La integridad de la informaci\u00F3n almacenada en srckeystore*\n* NO se ha comprobado.  Para comprobar dicha integridad, *\n* debe proporcionar la contrase\u00F1a de srckeystore.                *" },
            { ".The.integrity.of.the.information.stored.in.your.keystore.", "* La integridad de la informaci\u00F3n almacenada en el almac\u00E9n de claves  *\n* NO se ha comprobado.  Para comprobar dicha integridad, *\n* debe proporcionar la contrase\u00F1a del almac\u00E9n de claves.                  *" },
            { ".WARNING.WARNING.WARNING.", "*****************  WARNING WARNING WARNING  *****************" },
            { ".defaultValue.", "  [{0}]:  " },
            { ".is.not.trusted.", "... no es de confianza. " },
            { ".keypass.and.new.can.not.be.specified.if.storetype.is.{0}", "-keypass y -new no se pueden especificar si -storetype es {0}" },
            { ".keypasswd.commands.not.supported.if.storetype.is.PKCS12", "Los comandos -keypasswd no est\u00E1n soportados si -storetype es PKCS12" },
            { ".keystore.must.be.NONE.if.storetype.is.{0}", "-keystore debe ser NONE si -storetype es {0}" },
            { ".storepasswd.and.keypasswd.commands.not.supported.if.storetype.is.{0}", "Los comandos -storepasswd y -keypasswd no est\u00E1n soportados si -storetype es {0}" },
            { "Alias.alias.does.not.exist", "El alias <{0}> no existe" },
            { "Alias.alias.has.no.certificate", "El alias <{0}> no tiene certificado" },
            { "Alias.alias.has.no.key", "El alias <{0}> no tiene clave" },
            { "Alias.alias.references.an.entry.type.that.is.not.a.private.key.entry.The.keyclone.command.only.supports.cloning.of.private.key", "El alias <{0}> hace referencia a un tipo de entrada que no es una clave privada. El comando -keyclone s\u00F3lo permite la clonaci\u00F3n de entradas de claves privadas" },
            { "Alias.name.alias", "Nombre de Alias: {0}" },
            { "CRLs.", "CRL:" },
            { "Cannot.derive.signature.algorithm", "No se puede derivar el algoritmo de firma" },
            { "Cannot.find.environment.variable.", "No se ha encontrado la variable del entorno: " },
            { "Cannot.find.file.", "No se ha encontrado el archivo: " },
            { "Certificate.already.exists.in.keystore.under.alias.trustalias.", "El certificado ya existe en el almac\u00E9n de claves con el alias <{0}>" },
            { "Certificate.already.exists.in.system.wide.CA.keystore.under.alias.trustalias.", "El certificado ya existe en el almac\u00E9n de claves de la CA del sistema, con el alias <{0}>" },
            { "Certificate.chain.in.reply.does.not.verify.", "La cadena de certificado de la respuesta no verifica: " },
            { "Certificate.chain.length.", "Longitud de la Cadena de Certificado: " },
            { "Certificate.fingerprint.SHA.256.", "Huella de certificado (SHA-256): " },
            { "Certificate.i.1.", "Certificado[{0,number,integer}]:" },
            { "Certificate.not.imported.alias.alias.already.exists", "Certificado no importado, el alias <{0}> ya existe" },
            { "Certificate.owner.", "Propietario del Certificado: " },
            { "Certificate.reply.and.certificate.in.keystore.are.identical", "La respuesta del certificado y el certificado en el almac\u00E9n de claves son id\u00E9nticos" },
            { "Certificate.reply.does.not.contain.public.key.for.alias.", "La respuesta de certificado no contiene una clave p\u00FAblica para <{0}>" },
            { "Certificate.reply.was.installed.in.keystore", "Se ha instalado la respuesta del certificado en el almac\u00E9n de claves" },
            { "Certificate.reply.was.not.installed.in.keystore", "No se ha instalado la respuesta del certificado en el almac\u00E9n de claves" },
            { "Certificate.stored.in.file.filename.", "Certificado almacenado en el archivo <{0}>" },
            { "Certificate.was.added.to.keystore", "Se ha agregado el certificado al almac\u00E9n de claves" },
            { "Certificate.was.not.added.to.keystore", "No se ha agregado el certificado al almac\u00E9n de claves" },
            { "Certification.request.stored.in.file.filename.", "Solicitud de certificaci\u00F3n almacenada en el archivo <{0}>" },
            { "Changes.an.entry.s.alias", "Cambia un alias de entrada" },
            { "Changes.the.key.password.of.an.entry", "Cambia la contrase\u00F1a de clave de una entrada" },
            { "Changes.the.store.password.of.a.keystore", "Cambia la contrase\u00F1a de almac\u00E9n de un almac\u00E9n de claves" },
            { "Clones.a.key.entry", "Clona una entrada de clave" },
            { "Command.option.flag.needs.an.argument.", "La opci\u00F3n de comando {0} necesita un argumento." },
            { "Commands.", "Comandos:" },
            { "Creating.keystore.entry.for.id.getName.", "Creando entrada de almac\u00E9n de claves para <{0}> ..." },
            { "Creation.date.keyStore.getCreationDate.alias.", "Fecha de Creaci\u00F3n: {0,date}" },
            { "Deletes.an.entry", "Suprime una entrada" },
            { "Destination.alias.dest.already.exists", "El alias de destino <{0}> ya existe" },
            { "Do.you.still.want.to.add.it.no.", "\u00BFA\u00FAn desea agregarlo? [no]:  " },
            { "Do.you.still.want.to.add.it.to.your.own.keystore.no.", "\u00BFA\u00FAn desea agregarlo a su propio almac\u00E9n de claves? [no]:  " },
            { "Empty.input", "Entrada vac\u00EDa" },
            { "Enter.alias.name.", "Introduzca el nombre de alias:  " },
            { "Enter.destination.keystore.password.", "Introduzca la contrase\u00F1a de almac\u00E9n de claves de destino:  " },
            { "Enter.key.password.for.alias.", "Introduzca la contrase\u00F1a de clave para <{0}>" },
            { "Enter.keystore.password.", "Introduzca la contrase\u00F1a del almac\u00E9n de claves:  " },
            { "Enter.new.alias.name.RETURN.to.cancel.import.for.this.entry.", "Indique el nuevo nombre de alias\t(INTRO para cancelar la importaci\u00F3n de esta entrada):  " },
            { "Enter.prompt.alias.name.", "Escriba el nombre de alias de {0}:  " },
            { "Enter.source.keystore.password.", "Introduzca la contrase\u00F1a de almac\u00E9n de claves de origen:  " },
            { "Enter.the.password.to.be.stored.", "Introduzca la contrase\u00F1a que se va a almacenar:  " },
            { "Entry.for.alias.alias.not.imported.", "La entrada del alias {0} no se ha importado." },
            { "Entry.for.alias.alias.successfully.imported.", "La entrada del alias {0} se ha importado correctamente." },
            { "Entry.type.type.", "Tipo de Entrada: {0}" },
            { "Existing.entry.alias.alias.exists.overwrite.no.", "El alias de entrada existente {0} ya existe, \u00BFdesea sobrescribirlo? [no]:  " },
            { "Exports.certificate", "Exporta el certificado" },
            { "Extension.Request.", "Solicitud de Extensi\u00F3n:" },
            { "Extensions.", "Extensiones: " },
            { "Failed.to.establish.chain.from.reply", "No se ha podido definir una cadena a partir de la respuesta" },
            { "Failed.to.parse.input", "Fallo al analizar la entrada" },
            { "Generated.keyAlgName.secret.key", "Clave secreta {0} generada" },
            { "Generated.keysize.bit.keyAlgName.secret.key", "Clave secreta {1} de {0} bits generada" },
            { "Generates.CRL", "Genera CRL" },
            { "Generates.a.certificate.request", "Genera una solicitud de certificado" },
            { "Generates.a.key.pair", "Genera un par de claves" },
            { "Generates.a.secret.key", "Genera un clave secreta" },
            { "Generates.a.self.signed.certificate", "Genera un certificado autofirmado" },
            { "Generates.certificate.from.a.certificate.request", "Genera un certificado a partir de una solicitud de certificado" },
            { "Generating.keysize.bit.keyAlgName.key.pair.and.self.signed.certificate.sigAlgName.with.a.validity.of.validality.days.for", "Generando par de claves {1} de {0} bits para certificado autofirmado ({2}) con una validez de {3} d\u00EDas\n\tpara: {4}" },
            { "Illegal.option.", "Opci\u00F3n no permitida:  " },
            { "Illegal.startdate.value", "Valor de fecha de inicio no permitido" },
            { "Illegal.value.", "Valor no permitido: " },
            { "Import.command.completed.ok.entries.successfully.imported.fail.entries.failed.or.cancelled", "Comando de importaci\u00F3n completado: {0} entradas importadas correctamente, {1} entradas incorrectas o canceladas" },
            { "Imports.a.certificate.or.a.certificate.chain", "Importa un certificado o una cadena de certificados" },
            { "Imports.a.password", "Importa una contrase\u00F1a" },
            { "Imports.entries.from.a.JDK.1.1.x.style.identity.database", "Importa entradas desde una base de datos de identidades JDK 1.1.x-style" },
            { "Imports.one.or.all.entries.from.another.keystore", "Importa una o todas las entradas desde otro almac\u00E9n de claves" },
            { "Incomplete.certificate.chain.in.reply", "Cadena de certificado incompleta en la respuesta" },
            { "Input.not.an.X.509.certificate", "La entrada no es un certificado X.509" },
            { "Install.reply.anyway.no.", "\u00BFInstalar respuesta de todos modos? [no]:  " },
            { "Is.name.correct.", "\u00BFEs correcto {0}?" },
            { "Key.and.Certificate.Management.Tool", "Herramienta de Gesti\u00F3n de Certificados y Claves" },
            { "Key.pair.not.generated.alias.alias.already.exists", "No se ha generado el par de claves, el alias <{0}> ya existe" },
            { "Key.password.is.too.short.must.be.at.least.6.characters", "La contrase\u00F1a de clave es demasiado corta; debe tener al menos 6 caracteres" },
            { "Key.password.must.be.at.least.6.characters", "La contrase\u00F1a de clave debe tener al menos 6 caracteres" },
            { "Keystore.entry.for.id.getName.already.exists", "La entrada de almac\u00E9n de claves para <{0}> ya existe" },
            { "Keystore.file.does.not.exist.", "El archivo de almac\u00E9n de claves no existe: " },
            { "Keystore.file.exists.but.is.empty.", "El archivo de almac\u00E9n de claves existe, pero est\u00E1 vac\u00EDo: " },
            { "Keystore.password.is.too.short.must.be.at.least.6.characters", "La contrase\u00F1a del almac\u00E9n de claves es demasiado corta, debe tener al menos 6 caracteres" },
            { "Keystore.password.must.be.at.least.6.characters", "La contrase\u00F1a del almac\u00E9n de claves debe tener al menos 6 caracteres" },
            { "Keystore.provider.", "Proveedor de Almac\u00E9n de Claves: " },
            { "Keystore.type.", "Tipo de Almac\u00E9n de Claves: " },
            { "Lists.entries.in.a.keystore", "Enumera las entradas de un almac\u00E9n de claves" },
            { "Must.not.specify.both.v.and.rfc.with.list.command", "No se deben especificar -v y -rfc simult\u00E1neamente con el comando 'list'" },
            { "Must.specify.alias", "Se debe especificar un alias" },
            { "Must.specify.destination.alias", "Se debe especificar un alias de destino" },
            { "NEWLINE", "\n" },
            { "NO", "NO" },
            { "New.certificate.self.signed.", "Nuevo Certificado (Autofirmado):" },
            { "New.password.must.be.at.least.6.characters", "La nueva contrase\u00F1a debe tener al menos 6 caracteres" },
            { "New.prompt.", "Nuevo {0}: " },
            { "No.certificate.from.the.SSL.server", "Ning\u00FAn certificado del servidor SSL" },
            { "No.entries.from.identity.database.added", "No se han agregado entradas de la base de datos de identidades" },
            { "Not.X.509.certificate", "No es un certificado X.509" },
            { "Not.a.signed.jar.file", "No es un archivo jar firmado" },
            { "Odd.number.of.hex.digits.found.", "Se ha encontrado un n\u00FAmero impar de d\u00EDgitos hexadecimales: " },
            { "Options.", "Opciones:" },
            { "PKCS.10.with.weak", "Solicitud de certificado PKCS #10 (Versi\u00F3n 1.0)\nAsunto: %1$s\nFormato: %2$s\nClave p\u00FAblica: %3$s\nAlgoritmo de firma: %4$s\n" },
            { "Password.is.too.short.must.be.at.least.6.characters", "La contrase\u00F1a es demasiado corta; debe tener al menos 6 caracteres" },
            { "Passwords.must.differ", "Las contrase\u00F1as deben ser distintas" },
            { "Please.provide.keysize.for.secret.key.generation", "Proporcione el valor de -keysize para la generaci\u00F3n de claves secretas" },
            { "Please.specify.srckeystore", "Especifique -srckeystore" },
            { "Prints.the.content.of.a.CRL.file", "Imprime el contenido de un archivo CRL" },
            { "Prints.the.content.of.a.certificate", "Imprime el contenido de un certificado" },
            { "Prints.the.content.of.a.certificate.request", "Imprime el contenido de una solicitud de certificado" },
            { "Problem.importing.entry.for.alias.alias.exception.Entry.for.alias.alias.not.imported.", "Problema al importar la entrada del alias {0}: {1}.\nNo se ha importado la entrada del alias {0}." },
            { "Public.keys.in.reply.and.keystore.don.t.match", "Las claves p\u00FAblicas en la respuesta y en el almac\u00E9n de claves no coinciden" },
            { "Re.enter.new.password.", "Volver a escribir la contrase\u00F1a nueva: " },
            { "Re.enter.new.prompt.", "Vuelva a escribir el nuevo {0}: " },
            { "Re.enter.password.", "Vuelva a introducir la contrase\u00F1a: " },
            { "Reply.has.no.certificates", "La respuesta no tiene certificados" },
            { "SSL.server.host.and.port", "puerto y host del servidor SSL" },
            { "STAR", "*******************************************" },
            { "STARNN", "*******************************************\n\n" },
            { "Secret.key.not.generated.alias.alias.already.exists", "No se ha generado la clave secreta, el alias <{0}> ya existe" },
            { "Serial.ID.of.cert.to.revoke", "identificador de serie del certificado que se va a revocar" },
            { "Signature.", "Firma:" },
            { "Signer.d.", "#%d de Firmante:" },
            { "Source.keystore.file.exists.but.is.empty.", "El archivo de almac\u00E9n de claves de origen existe, pero est\u00E1 vac\u00EDo: " },
            { "Submit.this.to.your.CA", "Enviar a la CA" },
            { "The.destination.pkcs12.keystore.has.different.storepass.and.keypass.Please.retry.with.destkeypass.specified.", "El almac\u00E9n de claves pkcs12 de destino tiene storepass y keypass diferentes. Vuelva a intentarlo con -destkeypass especificado." },
            { "They.don.t.match.Try.again", "No coinciden. Int\u00E9ntelo de nuevo" },
            { "This.extension.cannot.be.marked.as.critical.", "Esta extensi\u00F3n no se puede marcar como cr\u00EDtica. " },
            { "Timestamp.", "Registro de Hora:" },
            { "Too.many.failures.Alias.not.changed", "Demasiados fallos. No se ha cambiado el alias" },
            { "Too.many.failures.Key.entry.not.cloned", "Demasiados fallos. No se ha clonado la entrada de clave" },
            { "Too.many.failures.key.not.added.to.keystore", "Demasiados fallos; no se ha agregado la clave al almac\u00E9n de claves" },
            { "Too.many.failures.try.later", "Demasiados fallos; int\u00E9ntelo m\u00E1s adelante" },
            { "Too.many.retries.program.terminated", "Ha habido demasiados intentos, se ha cerrado el programa" },
            { "Top.level.certificate.in.reply.", "Certificado de nivel superior en la respuesta:\n" },
            { "Trust.this.certificate.no.", "\u00BFConfiar en este certificado? [no]:  " },
            { "Unknown.AccessDescription.type.", "Tipo de descripci\u00F3n de acceso desconocido: " },
            { "Unknown.Entry.Type", "Tipo de Entrada Desconocido" },
            { "Unknown.extendedkeyUsage.type.", "Tipo de uso de clave extendida desconocido: " },
            { "Unknown.extension.type.", "Tipo de extensi\u00F3n desconocida: " },
            { "Unknown.keyUsage.type.", "Tipo de uso de clave desconocido: " },
            { "Unknown.password.type.", "Tipo de contrase\u00F1a desconocido: " },
            { "Unrecognized.GeneralName.type.", "Tipo de nombre general no reconocido: " },
            { "Usage.error.no.command.provided", "Error de sintaxis: no se ha proporcionado ning\u00FAn comando" },
            { "Use.keytool.command.name.help.for.usage.of.command.name", "Utilice \"keytool -command_name -help\" para la sintaxis de nombre_comando.\nUtilice la opci\u00F3n -conf <url> para especificar un archivo de opciones preconfigurado." },
            { "Use.keytool.help.for.all.available.commands", "Utilice \"keytool -help\" para todos los comandos disponibles" },
            { "Validity.must.be.greater.than.zero", "La validez debe ser mayor que cero" },
            { "Warning.Different.store.and.key.passwords.not.supported.for.PKCS12.KeyStores.Ignoring.user.specified.command.value.", "Advertencia: los almacenes de claves en formato PKCS12 no admiten contrase\u00F1as de clave y almacenamiento distintas. Se ignorar\u00E1 el valor especificado por el usuario, {0}." },
            { "Warning.Overwriting.existing.alias.alias.in.destination.keystore", "Advertencia: se sobrescribir\u00E1 el alias {0} en el almac\u00E9n de claves de destino" },
            { "What.is.the.name.of.your.City.or.Locality.", "\u00BFCu\u00E1l es el nombre de su ciudad o localidad?" },
            { "What.is.the.name.of.your.State.or.Province.", "\u00BFCu\u00E1l es el nombre de su estado o provincia?" },
            { "What.is.the.name.of.your.organization.", "\u00BFCu\u00E1l es el nombre de su organizaci\u00F3n?" },
            { "What.is.the.name.of.your.organizational.unit.", "\u00BFCu\u00E1l es el nombre de su unidad de organizaci\u00F3n?" },
            { "What.is.the.two.letter.country.code.for.this.unit.", "\u00BFCu\u00E1l es el c\u00F3digo de pa\u00EDs de dos letras de la unidad?" },
            { "What.is.your.first.and.last.name.", "\u00BFCu\u00E1les son su nombre y su apellido?" },
            { "Wrong.answer.try.again", "Respuesta incorrecta, vuelva a intentarlo" },
            { "X.509.extension", "extensi\u00F3n X.509" },
            { "YES", "S\u00CD" },
            { "Your.keystore.contains.keyStore.size.entries", "Su almac\u00E9n de claves contiene {0,number,integer} entradas" },
            { "Your.keystore.contains.keyStore.size.entry", "Su almac\u00E9n de claves contiene {0,number,integer} entrada" },
            { "access.the.cacerts.keystore", "acceso al almac\u00E9n de claves cacerts" },
            { "addprovider.option", "agregar proveedor de seguridad por nombre (por ejemplo, SunPKCS11)\nconfigurar elemento para -addprovider" },
            { "alias.", "{0}, " },
            { "alias.has.no.X.509.certificate", "{0} no tiene certificado X.509" },
            { "alias.has.no.public.key", "{0} no tiene clave p\u00FAblica" },
            { "alias.has.no.public.key.certificate.", "{0} no tiene clave p\u00FAblica (certificado)" },
            { "alias.in.cacerts", "Emisor <%s> en cacerts" },
            { "alias.in.keystore", "Emisor <%s>" },
            { "alias.keyStore.getCreationDate.alias.", "{0}, {1,date}, " },
            { "alias.name.of.the.entry.to.process", "nombre de alias de la entrada que se va a procesar" },
            { "backup.keystore.warning", "La copia de seguridad del almac\u00E9n de claves \"%1$s\" se ha realizado como \"%3$s\"..." },
            { "certificate.validity.start.date.time", "fecha/hora de inicio de validez del certificado" },
            { "command.{0}.is.ambiguous.", "El comando {0} es ambiguo:" },
            { "destination.alias", "alias de destino" },
            { "destination.key.password", "contrase\u00F1a de clave de destino" },
            { "destination.keystore.name", "nombre de almac\u00E9n de claves de destino" },
            { "destination.keystore.password", "contrase\u00F1a de almac\u00E9n de claves de destino" },
            { "destination.keystore.password.protected", "almac\u00E9n de claves de destino protegido por contrase\u00F1a" },
            { "destination.keystore.provider.name", "nombre de proveedor de almac\u00E9n de claves de destino" },
            { "destination.keystore.type", "tipo de almac\u00E9n de claves de destino" },
            { "distinguished.name", "nombre distintivo" },
            { "do.not.prompt", "no solicitar" },
            { "if.alias.not.specified.destalias.and.srckeypass.must.not.be.specified", "si no se especifica el alias, no se debe especificar destalias ni srckeypass" },
            { "if.keystore.is.not.password.protected.then.storepass.keypass.and.new.must.not.be.specified", "Si keystore no est\u00E1 protegido por contrase\u00F1a, no se deben especificar -storepass, -keypass ni -new" },
            { "if.protected.is.specified.then.storepass.keypass.and.new.must.not.be.specified", "si se especifica -protected, no deben especificarse -storepass, -keypass ni -new" },
            { "if.source.keystore.is.not.password.protected.then.srcstorepass.and.srckeypass.must.not.be.specified", "Si el almac\u00E9n de claves de origen no est\u00E1 protegido por contrase\u00F1a, no se deben especificar -srcstorepass ni -srckeypass" },
            { "if.srcprotected.is.specified.then.srcstorepass.and.srckeypass.must.not.be.specified", "Si se especifica -srcprotected, no se puede especificar -srcstorepass ni -srckeypass" },
            { "importing.keystore.status", "Importando el almac\u00E9n de claves de %1$s a %2$s..." },
            { "input.file.name", "nombre de archivo de entrada" },
            { "jks.storetype.warning", "El almac\u00E9n de claves %1$s utiliza un formato propietario. Se recomienda migrar a PKCS12, que es un formato est\u00E1ndar del sector que utiliza \"keytool -importkeystore -srckeystore %2$s -destkeystore %2$s -deststoretype pkcs12\"." },
            { "key.algorithm.name", "nombre de algoritmo de clave" },
            { "key.bit", "Clave %2$s de %1$d bits" },
            { "key.bit.size", "tama\u00F1o de bit de clave" },
            { "key.bit.weak", "Clave %2$s de %1$d bits (d\u00E9bil)" },
            { "key.password", "contrase\u00F1a de clave" },
            { "key.password.for.alias.", "contrase\u00F1a de clave para <{0}>" },
            { "keystore.name", "nombre de almac\u00E9n de claves" },
            { "keystore.password", "contrase\u00F1a de almac\u00E9n de claves" },
            { "keystore.type", "tipo de almac\u00E9n de claves" },
            { "keytool.error.", "error de herramienta de claves: " },
            { "migrate.keystore.warning", "Se ha migrado \"%1$s\" a %4$s. Se ha realizado la copia de seguridad del almac\u00E9n de claves %2$s como \"%3$s\"." },
            { "multiple.commands.1.2", "Solo se permite un comando: se ha especificado tanto %1$s como %2$s" },
            { "n", "n" },
            { "new.password", "nueva contrase\u00F1a" },
            { "no", "no" },
            { "one.in.many", "%1$s #%2$d de %3$d" },
            { "option.1.set.twice", "La opci\u00F3n %s se\u00A0ha especificado\u00A0varias veces. Se ignorar\u00E1n todas excepto la \u00FAltima." },
            { "output.file.name", "nombre de archivo de salida" },
            { "output.in.RFC.style", "salida en estilo RFC" },
            { "password.through.protected.mechanism", "contrase\u00F1a a trav\u00E9s de mecanismo protegido" },
            { "provclass.not.a.provider", "%s no es un proveedor" },
            { "provider.class.not.found", "No se ha encontrado el proveedor \"%s\"" },
            { "provider.class.option", "agregar proveedor de seguridad por nombre de clase totalmente cualificado\nconfigurar argumento para -providerclass" },
            { "provider.classpath", "classpath de proveedor" },
            { "provider.name", "nombre del proveedor" },
            { "provider.name.not.found", "No se ha encontrado el proveedor denominado \"%s\"" },
            { "reply", "Responder" },
            { "signature.algorithm.name", "nombre de algoritmo de firma" },
            { "signed.jar.file", "archivo jar firmado" },
            { "source.alias", "alias de origen" },
            { "source.key.password", "contrase\u00F1a de clave de origen" },
            { "source.keystore.name", "nombre de almac\u00E9n de claves de origen" },
            { "source.keystore.password", "contrase\u00F1a de almac\u00E9n de claves de origen" },
            { "source.keystore.password.protected", "almac\u00E9n de claves de origen protegido por contrase\u00F1a" },
            { "source.keystore.provider.name", "nombre de proveedor de almac\u00E9n de claves de origen" },
            { "source.keystore.type", "tipo de almac\u00E9n de claves de origen" },
            { "the.certificate", "El certificado" },
            { "the.certificate.request", "La solicitud de certificado" },
            { "the.crl", "La CRL" },
            { "the.generated.certificate", "El certificado generado" },
            { "the.generated.certificate.request", "La solicitud de certificado generada" },
            { "the.generated.crl", "La CRL generada" },
            { "the.input", "La entrada" },
            { "the.issuer", "El emisor" },
            { "the.keystore.or.storetype.option.cannot.be.used.with.the.cacerts.option", "Las opciones -keystore o -storetype no se pueden utilizar con la opci\u00F3n -cacerts" },
            { "the.tsa.certificate", "El certificado de TSA" },
            { "trust.certificates.from.cacerts", "certificados de protecci\u00F3n de cacerts" },
            { "unknown.size.1", "clave %s de tama\u00F1o desconocido" },
            { "validity.number.of.days", "n\u00FAmero de validez de d\u00EDas" },
            { "verbose.output", "salida detallada" },
            { "verified.by.s.in.s.weak", "Verificado por %1$s en %2$s con %3$s" },
            { "warning.cacerts.option", "Advertencia: Utilice la opci\u00F3n -cacerts para acceder al almac\u00E9n de claves cacerts" },
            { "warning.not.verified.make.sure.keystore.is.correct", "ADVERTENCIA: no se ha verificado. Aseg\u00FArese de que el valor de -keystore es correcto." },
            { "whose.key.risk", "%1$s utiliza %2$s, lo que se considera riesgo de seguridad." },
            { "whose.sigalg.risk", "%1$s utiliza el algoritmo de firma %2$s, lo que se considera un riesgo de seguridad." },
            { "with.weak", "%s (d\u00E9bil)" },
            { "y", "s" },
            { "yes", "s\u00ED" },
        };
    }
}
